In [4]:
# -*- encoding:urf-8 -*-
# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

# Handle table like and matrices
import pandas as pd
import numpy as np

# Modeling Helper
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
import seaborn as sns
import missingno as msno

# Configure visualization
%matplotlib inline
mpl.style.use('ggplot')
sns.set_style('white')
pylab.rcParams['figure.figsize'] = 8,6

poi_path = '../../UAI_data/input/poi_re.csv'
train_Aug_path = '../../UAI_data/input/train_Aug_re.csv'
train_Jul_path = '../../UAI_data/input/train_July_re.csv'
train_jul_demand_path = '../../UAI_data/input/tain_jul_demand.csv'
train_aug_demand_path = '../../UAI_data/input/tain_aug_demand.csv'
location_path = '../../UAI_data/input/location_cls.csv'
holiday_path = '../../UAI_data/input/holiday.csv'
weather_path = '../../UAI_data/input/weather.csv'
test_path = '../../UAI_data/input/test.csv'

poi = pd.read_csv(poi_path,encoding='gbk')
train_aug = pd.read_csv(train_Aug_path,encoding='gbk')
train_jul = pd.read_csv(train_Jul_path,encoding='gbk')
train_jul_demand = pd.read_csv(train_jul_demand_path,encoding='gbk')
train_aug_demand = pd.read_csv(train_aug_demand_path,encoding='gbk')
loc_cls = pd.read_csv(location_path)
holiday = pd.read_csv(holiday_path)
weather = pd.read_csv(weather_path)
test = pd.read_csv(test_path,encoding='gbk')

### Helper Functions

In [25]:
def plot_histograms( df , variables , n_rows , n_cols ):
    fig = plt.figure( figsize = ( 16 , 12 ) )
    for i, var_name in enumerate( variables ):
        ax=fig.add_subplot( n_rows , n_cols , i+1 )
        df[ var_name ].hist( bins=10 , ax=ax )
        ax.set_title( 'Skew: ' + str( round( float( df[ var_name ].skew() ) , ) ) ) # + ' ' + var_name ) #var_name+" Distribution")
        ax.set_xticklabels( [] , visible=False )
        ax.set_yticklabels( [] , visible=False )
    fig.tight_layout()  # Improves appearance a bit.
    plt.show()

def plot_distribution( df , var , target , **kwargs ):
    row = kwargs.get( 'row' , None )
    col = kwargs.get( 'col' , None )
    facet = sns.FacetGrid( df , hue=target , aspect=4 , row = row , col = col )
    facet.map( sns.kdeplot , var , shade= True )
    facet.set( xlim=( 0 , df[ var ].max() ) )
    facet.add_legend()

def plot_categories( df , cat , target , **kwargs ):
    row = kwargs.get( 'row' , None )
    col = kwargs.get( 'col' , None )
    facet = sns.FacetGrid( df , row = row , col = col )
    facet.map( sns.barplot , cat , target )
    facet.add_legend()

def plot_correlation_map( df ):
    corr = df.corr()
    _ , ax = plt.subplots( figsize =( 12 , 10 ) )
    cmap = sns.diverging_palette( 220 , 10 , as_cmap = True )
    _ = sns.heatmap(
        corr, 
        cmap = cmap,
        square=True, 
        cbar_kws={ 'shrink' : .9 }, 
        ax=ax, 
        annot = True, 
        annot_kws = { 'fontsize' : 12 }
    )

def describe_more( df ):
    var = [] ; l = [] ; t = []
    for x in df:
        var.append( x )
        l.append( len( pd.value_counts( df[ x ] ) ) )
        t.append( df[ x ].dtypes )
    levels = pd.DataFrame( { 'Variable' : var , 'Levels' : l , 'Datatype' : t } )
    levels.sort_values( by = 'Levels' , inplace = True )
    return levels

def plot_variable_importance( X , y ):
    tree = DecisionTreeClassifier( random_state = 99 )
    tree.fit( X , y )
    plot_model_var_imp( tree , X , y )
    
def plot_model_var_imp( model , X , y ):
    imp = pd.DataFrame( 
        model.feature_importances_  , 
        columns = [ 'Importance' ] , 
        index = X.columns 
    )
    imp = imp.sort_values( [ 'Importance' ] , ascending = True )
    imp[ : 10 ].plot( kind = 'barh' )
    print (model.score( X , y ))

In [8]:
coord = train_jul.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_money'].agg({'estimate_money_mean':'mean'})
coord

       create_date  create_hour  start_geo_id  end_geo_id  estimate_money_mean
0       2017-07-01            0             0          10           101.000000
1       2017-07-01            0             0          21            39.000000
2       2017-07-01            0             0          64            78.860000
3       2017-07-01            0             1           1            28.500000
4       2017-07-01            0             1          15            67.000000
5       2017-07-01            0             1          37            63.000000
6       2017-07-01            0             1          39            67.110000
7       2017-07-01            0             1          89            59.675000
8       2017-07-01            0             1          95            90.000000
9       2017-07-01            0             1         160            46.520000
10      2017-07-01            0             1         303            66.000000
11      2017-07-01            0             2           2           233.000000
12      2017-07-01            0             2           5           234.290000
13      2017-07-01            0             2          38            71.901429
14      2017-07-01            0             2          46           149.892000
15      2017-07-01            0             2         265           315.000000
16      2017-07-01            0             3          80            52.000000
17      2017-07-01            0             4          97            37.000000
18      2017-07-01            0             5           0           140.083333
19      2017-07-01            0             5           1           206.000000
20      2017-07-01            0             5           8           129.566667
21      2017-07-01            0             5           9           192.633333
22      2017-07-01            0             5          18           125.733333
23      2017-07-01            0             5          22           146.710000
24      2017-07-01            0             5          29           201.000000
25      2017-07-01            0             5          30           284.135000
26      2017-07-01            0             5          31           380.000000
27      2017-07-01            0             5          34           240.000000
28      2017-07-01            0             5          39           151.160000
29      2017-07-01            0             5          51           132.980000
...            ...          ...           ...         ...                  ...
501315  2017-07-31           23           114          56            78.000000
501316  2017-07-31           23           114          76            82.625000
501317  2017-07-31           23           118          25            23.000000
501318  2017-07-31           23           118         118            26.000000
501319  2017-07-31           23           118         119            45.000000
501320  2017-07-31           23           119          44            32.000000
501321  2017-07-31           23           119          90            67.000000
501322  2017-07-31           23           124         157            53.000000
501323  2017-07-31           23           126         108            81.180000
501324  2017-07-31           23           135          17            36.000000
501325  2017-07-31           23           135          21            71.000000
501326  2017-07-31           23           140          90            74.000000
501327  2017-07-31           23           144          72            65.730000
501328  2017-07-31           23           147          33           164.000000
501329  2017-07-31           23           147         169            40.000000
501330  2017-07-31           23           149         122            96.440000
501331  2017-07-31           23           150          74            59.000000
501332  2017-07-31           23           150          96            50.000000
501333  2017-07-31           23           150         150            43.255000
501334  2017-07-31           23           155           3            71.910000
501335  2017-07-31           23           158          24            57.000000
501336  2017-07-31           23           167         146            61.000000
501337  2017-07-31           23           194           8           131.000000
501338  2017-07-31           23           195          42            61.000000
501339  2017-07-31           23           223          25            57.420000
501340  2017-07-31           23           245         175            71.000000
501341  2017-07-31           23           251          70           168.430000
501342  2017-07-31           23           360         105            34.770000
501343  2017-07-31           23           478          80           206.000000
501344  2017-07-31           23           579          60           129.710000

[501345 rows x 5 columns]

In [9]:
train_jul_demand

       create_date  create_hour  start_geo_id  end_geo_id  demand_count
0       2017-07-01            0             0          10             1
1       2017-07-01            0             0          21             1
2       2017-07-01            0             0          64             1
3       2017-07-01            0             1           1             2
4       2017-07-01            0             1          15             2
5       2017-07-01            0             1          37             1
6       2017-07-01            0             1          39             2
7       2017-07-01            0             1          89             2
8       2017-07-01            0             1          95             1
9       2017-07-01            0             1         160             2
10      2017-07-01            0             1         303             1
11      2017-07-01            0             2           2             1
12      2017-07-01            0             2           5             1
13      2017-07-01            0             2          38             7
14      2017-07-01            0             2          46             5
15      2017-07-01            0             2         265             1
16      2017-07-01            0             3          80             1
17      2017-07-01            0             4          97             1
18      2017-07-01            0             5           0             3
19      2017-07-01            0             5           1             1
20      2017-07-01            0             5           8             3
21      2017-07-01            0             5           9             3
22      2017-07-01            0             5          18             3
23      2017-07-01            0             5          22             5
24      2017-07-01            0             5          29             1
25      2017-07-01            0             5          30             2
26      2017-07-01            0             5          31             1
27      2017-07-01            0             5          34             1
28      2017-07-01            0             5          39             3
29      2017-07-01            0             5          51             3
...            ...          ...           ...         ...           ...
501315  2017-07-31           23           114          56             1
501316  2017-07-31           23           114          76             2
501317  2017-07-31           23           118          25             1
501318  2017-07-31           23           118         118             1
501319  2017-07-31           23           118         119             1
501320  2017-07-31           23           119          44             1
501321  2017-07-31           23           119          90             1
501322  2017-07-31           23           124         157             1
501323  2017-07-31           23           126         108             1
501324  2017-07-31           23           135          17             1
501325  2017-07-31           23           135          21             1
501326  2017-07-31           23           140          90             1
501327  2017-07-31           23           144          72             1
501328  2017-07-31           23           147          33             1
501329  2017-07-31           23           147         169             1
501330  2017-07-31           23           149         122             1
501331  2017-07-31           23           150          74             1
501332  2017-07-31           23           150          96             1
501333  2017-07-31           23           150         150             2
501334  2017-07-31           23           155           3             1
501335  2017-07-31           23           158          24             1
501336  2017-07-31           23           167         146             1
501337  2017-07-31           23           194           8             1
501338  2017-07-31           23           195          42             1
501339  2017-07-31           23           223          25             2
501340  2017-07-31           23           245         175             1
501341  2017-07-31           23           251          70             1
501342  2017-07-31           23           360         105             1
501343  2017-07-31           23           478          80             1
501344  2017-07-31           23           579          60             1

[501345 rows x 5 columns]

In [24]:
train_jul_exc = train_jul[train_jul['driver_id'] != 2].copy()
coord_jul = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['start_geo_id'].agg({'demand_count':'count'})
coord_jul.loc[:,'estimate_money_mean'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_money'].mean()['estimate_money']
coord_jul.loc[:,'estimate_money_median'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_money'].median()['estimate_money']
# coord_jul.loc[:,'estimate_money_std'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_money'].std()['estimate_money']
coord_jul.loc[:,'estimate_money_max'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_money'].max()['estimate_money']
coord_jul.loc[:,'estimate_money_min'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_money'].min()['estimate_money']
coord_jul.loc[:,'estimate_distance_mean'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_distance'].mean()['estimate_distance']
coord_jul.loc[:,'estimate_distance_median'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_distance'].median()['estimate_distance']
# coord_jul.loc[:,'estimate_distance_std'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_distance'].std()['estimate_distance']
coord_jul.loc[:,'estimate_distance_max'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_distance'].max()['estimate_distance']
coord_jul.loc[:,'estimate_distance_min'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_distance'].min()['estimate_distance']
coord_jul.loc[:,'estimate_term_mean'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_term'].mean()['estimate_term']
coord_jul.loc[:,'estimate_term_median'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_term'].median()['estimate_term']
# coord_jul.loc[:,'estimate_term_std'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_term'].std()['estimate_term']
coord_jul.loc[:,'estimate_term_max'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_term'].max()['estimate_term']
coord_jul.loc[:,'estimate_term_min'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_term'].min()['estimate_term']

coord_jul

,create_date,create_hour,start_geo_id,end_geo_id,demand_count,estimate_money_mean,estimate_money_median,estimate_money_max,estimate_money_min,estimate_distance_mean,estimate_distance_median,estimate_distance_max,estimate_distance_min,estimate_term_mean,estimate_term_median,estimate_term_max,estimate_term_min
0,2017-07-01,0,0,10,1,101.000,101.000,101.00,101.00,14431.0,14431.0,14431.0,14431.0,24.0,24.0,24.0,24.0
1,2017-07-01,0,0,21,1,39.000,39.000,39.00,39.00,4905.0,4905.0,4905.0,4905.0,9.0,9.0,9.0,9.0
2,2017-07-01,0,1,1,2,28.500,28.500,32.00,25.00,2437.0,2437.0,3220.0,1654.0,4.5,4.5,6.0,3.0
3,2017-07-01,0,1,15,2,67.000,67.000,73.00,61.00,10955.0,10955.0,12254.0,9656.0,21.5,21.5,24.0,19.0
4,2017-07-01,0,1,37,1,63.000,63.000,63.00,63.00,10010.0,10010.0,10010.0,10010.0,20.0,20.0,20.0,20.0
5,2017-07-01,0,1,39,2,67.110,67.110,67.41,66.81,11493.0,11493.0,11493.0,11493.0,17.5,17.5,18.0,17.0
6,2017-07-01,0,1,89,1,58.000,58.000,58.00,58.00,8905.0,8905.0,8905.0,8905.0,17.0,17.0,17.0,17.0
7,2017-07-01,0,1,95,1,90.000,90.000,90.00,90.00,15677.0,15677.0,15677.0,15677.0,31.0,31.0,31.0,31.0
8,2017-07-01,0,1,160,2,46.520,46.520,46.87,46.17,6347.0,6347.0,6453.0,6241.0,12.0,12.0,12.0,12.0
9,2017-07-01,0,1,303,1,66.000,66.000,66.00,66.00,11493.0,11493.0,11493.0,11493.0,17.0,17.0,17.0,17.0
10,2017-07-01,0,2,2,1,233.000,233.000,233.00,233.00,36363.0,36363.0,36363.0,36363.0,36.0,36.0,36.0,36.0
11,2017-07-01,0,2,38,5,64.982,59.930,89.00,56.00,6605.8,6596.0,6621.0,6595.0,13.0,13.0,13.0,13.0
12,2017-07-01,0,2,46,1,110.710,110.710,110.71,110.71,17460.0,17460.0,17460.0,17460.0,23.0,23.0,23.0,23.0
13,2017-07-01,0,2,265,1,315.000,315.000,315.00,315.00,41878.0,41878.0,41878.0,41878.0,49.0,49.0,49.0,49.0
14,2017-07-01,0,3,80,1,52.000,52.000,52.00,52.00,4728.0,4728.0,4728.0,4728.0,9.0,9.0,9.0,9.0
15,2017-07-01,0,4,97,1,37.000,37.000,37.00,37.00,4308.0,4308.0,4308.0,4308.0,8.0,8.0,8.0,8.0
16,2017-07-01,0,5,0,1,140.000,140.000,140.00,140.00,20099.0,20099.0,20099.0,20099.0,18.0,18.0,18.0,18.0
17,2017-07-01,0,5,1,1,206.000,206.000,206.00,206.00,27950.0,27950.0,27950.0,27950.0,33.0,33.0,33.0,33.0
18,2017-07-01,0,5,8,2,121.500,121.500,145.00,98.00,19427.0,19427.0,20482.0,18372.0,21.5,21.5,22.0,21.0
19,2017-07-01,0,5,29,1,201.000,201.000,201.00,201.00,27823.0,27823.0,27823.0,27823.0,28.0,28.0,28.0,28.0
20,2017-07-01,0,5,30,1,284.000,284.000,284.00,284.00,37830.0,37830.0,37830.0,37830.0,45.0,45.0,45.0,45.0
21,2017-07-01,0,5,31,1,380.000,380.000,380.00,380.00,36014.0,36014.0,36014.0,36014.0,35.0,35.0,35.0,35.0
22,2017-07-01,0,5,34,1,240.000,240.000,240.00,240.00,32813.0,32813.0,32813.0,32813.0,34.0,34.0,34.0,34.0
23,2017-07-01,0,5,39,2,147.000,147.000,159.00,135.00,23825.5,23825.5,25398.0,22253.0,23.0,23.0,23.0,23.0
24,2017-07-01,0,5,51,1,134.920,134.920,134.92,134.92,18680.0,18680.0,18680.0,18680.0,23.0,23.0,23.0,23.0
25,2017-07-01,0,5,63,1,163.000,163.000,163.00,163.00,21984.0,21984.0,21984.0,21984.0,30.0,30.0,30.0,30.0
26,2017-07-01,0,5,70,1,241.000,241.000,241.00,241.00,32615.0,32615.0,32615.0,32615.0,36.0,36.0,36.0,36.0
27,2017-07-01,0,5,71,1,200.000,200.000,200.00,200.00,26470.0,26470.0,26470.0,26470.0,38.0,38.0,38.0,38.0
28,2017-07-01,0,5,73,1,194.000,194.000,194.00,194.00,26601.0,26601.0,26601.0,26601.0,29.0,29.0,29.0,29.0
29,2017-07-01,0,5,102,1,128.000,128.000,128.00,128.00,18124.0,18124.0,18124.0,18124.0,20.0,20.0,20.0,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447489,2017-07-31,23,109,24,1,85.000,85.000,85.00,85.00,14812.0,14812.0,14812.0,14812.0,29.0,29.0,29.0,29.0
447490,2017-07-31,23,109,79,1,94.000,94.000,94.00,94.00,16836.0,16836.0,16836.0,16836.0,27.0,27.0,27.0,27.0
447491,2017-07-31,23,109,92,1,206.150,206.150,206.15,206.15,35307.0,35307.0,35307.0,35307.0,55.0,55.0,55.0,55.0
447492,2017-07-31,23,114,56,1,78.000,78.000,78.00,78.00,13353.0,13353.0,13353.0,13353.0,26.0,26.0,26.0,26.0
447493,2017-07-31,23,114,76,2,82.625,82.625,83.00,82.25,14957.0,14957.0,15013.0,14901.0,24.0,24.0,25.0,23.0
447494,2017-07-31,23,118,25,1,23.000,23.000,23.00,23.00,1179.0,1179.0,1179.0,1179.0,2.0,2.0,2.0,2.0
447495,2017-07-31,23,118,118,1,26.000,26.000,26.00,26.00,1913.0,1913.0,1913.0,1913.0,3.0,3.0,3.0,3.0
447496,2017-07-31,23,118,119,1,45.000,45.000,45.00,45.00,6389.0,6389.0,6389.0,6389.0,10.0,10.0,10.0,10.0
447497,2017-07-31,23,119,44,1,32.000,32.000,32.00,32.00,3154.0,3154.0,3154.0,3154.0,6.0,6.0,6.0,6.0
447498,2017-07-31,23,119,90,1,67.000,67.000,67.00,67.00,11256.0,11256.0,11256.0,11256.0,20.0,20.0,20.0,20.0
447499,2017-07-31,23,124,157,1,53.000,53.000,53.00,53.00,7900.0,7900.0,7900.0,7900.0,15.0,15.0,15.0,15.0
447500,2017-07-31,23,135,17,1,36.000,36.000,36.00,36.00,4116.0,4116.0,4116.0,4116.0,8.0,8.0,8.0,8.0
447501,2017-07-31,23,135,21,1,71.000,71.000,71.00,71.00,12721.0,12721.0,12721.0,12721.0,18.0,18.0,18.0,18.0
447502,2017-07-31,23,140,90,1,74.000,74.000,74.00,74.00,13715.0,13715.0,13715.0,13715.0,17.0,17.0,17.0,17.0
447503,2017-07-31,23,144,72,1,65.730,65.730,65.73,65.73,10999.0,10999.0,10999.0,10999.0,18.0,18.0,18.0,18.0
447504,2017-07-31,23,147,33,1,164.000,164.000,164.00,164.00,27290.0,27290.0,27290.0,27290.0,54.0,54.0,54.0,54.0
447505,2017-07-31,23,147,169,1,40.000,40.000,40.00,40.00,4974.0,4974.0,4974.0,4974.0,9.0,9.0,9.0,9.0
447506,2017-07-31,23,149,122,1,96.440,96.440,96.44,96.44,17186.0,17186.0,17186.0,17186.0,28.0,28.0,28.0,28.0
447507,2017-07-31,23,150,74,1,59.000,59.000,59.00,59.00,9280.0,9280.0,9280.0,9280.0,18.0,18.0,18.0,18.0
447508,2017-07-31,23,150,96,1,50.000,50.000,50.00,50.00,7043.0,7043.0,7043.0,7043.0,14.0,14.0,14.0,14.0
447509,2017-07-31,23,150,150,2,43.255,43.255,51.00,35.51,3968.0,3968.0,3968.0,3968.0,7.0,7.0,7.0,7.0
447510,2017-07-31,23,158,24,1,57.000,57.000,57.00,57.00,8666.0,8666.0,8666.0,8666.0,17.0,17.0,17.0,17.0
447511,2017-07-31,23,167,146,1,61.000,61.000,61.00,61.00,10784.0,10784.0,10784.0,10784.0,12.0,12.0,12.0,12.0
447512,2017-07-31,23,194,8,1,131.000,131.000,131.00,131.00,24066.0,24066.0,24066.0,24066.0,28.0,28.0,28.0,28.0
447513,2017-07-31,23,195,42,1,61.000,61.000,61.00,61.00,9610.0,9610.0,9610.0,9610.0,19.0,19.0,19.0,19.0
447514,2017-07-31,23,223,25,2,57.420,57.420,57.84,57.00,8828.0,8828.0,8828.0,8828.0,16.5,16.5,17.0,16.0
447515,2017-07-31,23,245,175,1,71.000,71.000,71.00,71.00,12165.0,12165.0,12165.0,12165.0,21.0,21.0,21.0,21.0
447516,2017-07-31,23,251,70,1,168.430,168.430,168.43,168.43,30206.0,30206.0,30206.0,30206.0,36.0,36.0,36.0,36.0
447517,2017-07-31,23,360,105,1,34.770,34.770,34.77,34.77,3749.0,3749.0,3749.0,3749.0,7.0,7.0,7.0,7.0
447518,2017-07-31,23,478,80,1,206.000,206.000,206.00,206.00,37641.0,37641.0,37641.0,37641.0,35.0,35.0,35.0,35.0

In [32]:
holiday['date'] = pd.to_datetime(holiday['date'])

0    2017-07-01
1    2017-07-02
2    2017-07-03
3    2017-07-04
4    2017-07-05
5    2017-07-06
6    2017-07-07
7    2017-07-08
8    2017-07-09
9    2017-07-10
10   2017-07-11
11   2017-07-12
12   2017-07-13
13   2017-07-14
14   2017-07-15
15   2017-07-16
16   2017-07-17
17   2017-07-18
18   2017-07-19
19   2017-07-20
20   2017-07-21
21   2017-07-22
22   2017-07-23
23   2017-07-24
24   2017-07-25
25   2017-07-26
26   2017-07-27
27   2017-07-28
28   2017-07-29
29   2017-07-30
30   2017-07-31
31   2017-08-01
32   2017-08-02
33   2017-08-03
34   2017-08-04
35   2017-08-05
36   2017-08-06
37   2017-08-07
Name: date, dtype: datetime64[ns]