In [1]:
# -*- encoding:urf-8 -*-
# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

# Handle table like and matrices
import pandas as pd
import numpy as np

# Modeling Helper
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
import seaborn as sns
import missingno as msno

# Configure visualization
%matplotlib inline
mpl.style.use('ggplot')
sns.set_style('white')
pylab.rcParams['figure.figsize'] = 8,6

poi_path = '../../UAI_data/input/poi_re.csv'
train_Aug_path = '../../UAI_data/input/train_Aug_re.csv'
train_Jul_path = '../../UAI_data/input/train_July_re.csv'
train_jul_demand_path = '../../UAI_data/input/tain_jul_demand.csv'
train_aug_demand_path = '../../UAI_data/input/tain_aug_demand.csv'
location_path = '../../UAI_data/input/location_cls.csv'
holiday_path = '../../UAI_data/input/holiday.csv'
weather_path = '../../UAI_data/input/weather.csv'
test_path = '../../UAI_data/input/test.csv'

poi = pd.read_csv(poi_path,encoding='gbk')
train_aug = pd.read_csv(train_Aug_path,encoding='gbk')
train_jul = pd.read_csv(train_Jul_path,encoding='gbk')
train_jul_demand = pd.read_csv(train_jul_demand_path,encoding='gbk')
train_aug_demand = pd.read_csv(train_aug_demand_path,encoding='gbk')
loc_cls = pd.read_csv(location_path)
holiday = pd.read_csv(holiday_path)
weather = pd.read_csv(weather_path)
test = pd.read_csv(test_path,encoding='gbk')

###  Helper Functions

In [2]:
def plot_histograms( df , variables , n_rows , n_cols ):
    fig = plt.figure( figsize = ( 16 , 12 ) )
    for i, var_name in enumerate( variables ):
        ax=fig.add_subplot( n_rows , n_cols , i+1 )
        df[ var_name ].hist( bins=10 , ax=ax )
        ax.set_title( 'Skew: ' + str( round( float( df[ var_name ].skew() ) , ) ) ) # + ' ' + var_name ) #var_name+" Distribution")
        ax.set_xticklabels( [] , visible=False )
        ax.set_yticklabels( [] , visible=False )
    fig.tight_layout()  # Improves appearance a bit.
    plt.show()

def plot_distribution( df , var , target , **kwargs ):
    row = kwargs.get( 'row' , None )
    col = kwargs.get( 'col' , None )
    facet = sns.FacetGrid( df , hue=target , aspect=4 , row = row , col = col )
    facet.map( sns.kdeplot , var , shade= True )
    facet.set( xlim=( 0 , df[ var ].max() ) )
    facet.add_legend()

def plot_categories( df , cat , target , **kwargs ):
    row = kwargs.get( 'row' , None )
    col = kwargs.get( 'col' , None )
    facet = sns.FacetGrid( df , row = row , col = col )
    facet.map( sns.barplot , cat , target )
    facet.add_legend()

def plot_correlation_map( df ):
    corr = df.corr()
    _ , ax = plt.subplots( figsize =( 12 , 10 ) )
    cmap = sns.diverging_palette( 220 , 10 , as_cmap = True )
    _ = sns.heatmap(
        corr, 
        cmap = cmap,
        square=True, 
        cbar_kws={ 'shrink' : .9 }, 
        ax=ax, 
        annot = True, 
        annot_kws = { 'fontsize' : 12 }
    )

def describe_more( df ):
    var = [] ; l = [] ; t = []
    for x in df:
        var.append( x )
        l.append( len( pd.value_counts( df[ x ] ) ) )
        t.append( df[ x ].dtypes )
    levels = pd.DataFrame( { 'Variable' : var , 'Levels' : l , 'Datatype' : t } )
    levels.sort_values( by = 'Levels' , inplace = True )
    return levels

def plot_variable_importance( X , y ):
    tree = DecisionTreeClassifier( random_state = 99 )
    tree.fit( X , y )
    plot_model_var_imp( tree , X , y )
    
def plot_model_var_imp( model , X , y ):
    imp = pd.DataFrame( 
        model.feature_importances_  , 
        columns = [ 'Importance' ] , 
        index = X.columns 
    )
    imp = imp.sort_values( [ 'Importance' ] , ascending = True )
    imp[ : 10 ].plot( kind = 'barh' )
    print (model.score( X , y ))

In [3]:
# train_jul_exc = train_jul[train_jul['driver_id'] != 2].copy()
train_jul_exc = train_jul.copy()
coord_jul = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['start_geo_id'].agg({'demand_count':'count'})
coord_jul.loc[:,'estimate_money_mean'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_money'].mean()['estimate_money']
# coord_jul.loc[:,'estimate_money_median'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_money'].median()['estimate_money']
# coord_jul.loc[:,'estimate_money_max'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_money'].max()['estimate_money']
# coord_jul.loc[:,'estimate_money_min'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_money'].min()['estimate_money']
coord_jul.loc[:,'estimate_distance_mean'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_distance'].mean()['estimate_distance']
# coord_jul.loc[:,'estimate_distance_median'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_distance'].median()['estimate_distance']
# coord_jul.loc[:,'estimate_distance_max'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_distance'].max()['estimate_distance']
# coord_jul.loc[:,'estimate_distance_min'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_distance'].min()['estimate_distance']
coord_jul.loc[:,'estimate_term_mean'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_term'].mean()['estimate_term']
# coord_jul.loc[:,'estimate_term_median'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_term'].median()['estimate_term']
# coord_jul.loc[:,'estimate_term_max'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_term'].max()['estimate_term']
# coord_jul.loc[:,'estimate_term_min'] = train_jul_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_term'].min()['estimate_term']

# coord_jul.to_csv('train_jul_exc.csv',index=False)
coord_jul

,create_date,create_hour,start_geo_id,end_geo_id,demand_count,estimate_money_mean,estimate_distance_mean,estimate_term_mean
0,2017-07-01,0,0,10,1,101.000000,14431.000000,24.000000
1,2017-07-01,0,0,21,1,39.000000,4905.000000,9.000000
2,2017-07-01,0,0,64,1,78.860000,8764.000000,9.000000
3,2017-07-01,0,1,1,2,28.500000,2437.000000,4.500000
4,2017-07-01,0,1,15,2,67.000000,10955.000000,21.500000
5,2017-07-01,0,1,37,1,63.000000,10010.000000,20.000000
6,2017-07-01,0,1,39,2,67.110000,11493.000000,17.500000
7,2017-07-01,0,1,89,2,59.675000,9208.500000,18.000000
8,2017-07-01,0,1,95,1,90.000000,15677.000000,31.000000
9,2017-07-01,0,1,160,2,46.520000,6347.000000,12.000000
10,2017-07-01,0,1,303,1,66.000000,11493.000000,17.000000
11,2017-07-01,0,2,2,1,233.000000,36363.000000,36.000000
12,2017-07-01,0,2,5,1,234.290000,36363.000000,37.000000
13,2017-07-01,0,2,38,7,71.901429,6602.714286,13.000000
14,2017-07-01,0,2,46,5,149.892000,17490.200000,22.600000
15,2017-07-01,0,2,265,1,315.000000,41878.000000,49.000000
16,2017-07-01,0,3,80,1,52.000000,4728.000000,9.000000
17,2017-07-01,0,4,97,1,37.000000,4308.000000,8.000000
18,2017-07-01,0,5,0,3,140.083333,20009.000000,18.333333
19,2017-07-01,0,5,1,1,206.000000,27950.000000,33.000000
20,2017-07-01,0,5,8,3,129.566667,19778.666667,21.333333
21,2017-07-01,0,5,9,3,192.633333,26606.000000,27.000000
22,2017-07-01,0,5,18,3,125.733333,17620.000000,20.666667
23,2017-07-01,0,5,22,5,146.710000,20771.800000,19.800000
24,2017-07-01,0,5,29,1,201.000000,27823.000000,28.000000
25,2017-07-01,0,5,30,2,284.135000,37830.000000,45.000000
26,2017-07-01,0,5,31,1,380.000000,36014.000000,35.000000
27,2017-07-01,0,5,34,1,240.000000,32813.000000,34.000000
28,2017-07-01,0,5,39,3,151.160000,23301.333333,23.000000
29,2017-07-01,0,5,51,3,132.980000,18438.333333,22.666667
...,...,...,...,...,...,...,...,...
501315,2017-07-31,23,114,56,1,78.000000,13353.000000,26.000000
501316,2017-07-31,23,114,76,2,82.625000,14957.000000,24.000000
501317,2017-07-31,23,118,25,1,23.000000,1179.000000,2.000000
501318,2017-07-31,23,118,118,1,26.000000,1913.000000,3.000000
501319,2017-07-31,23,118,119,1,45.000000,6389.000000,10.000000
501320,2017-07-31,23,119,44,1,32.000000,3154.000000,6.000000
501321,2017-07-31,23,119,90,1,67.000000,11256.000000,20.000000
501322,2017-07-31,23,124,157,1,53.000000,7900.000000,15.000000
501323,2017-07-31,23,126,108,1,81.180000,14343.000000,25.000000
501324,2017-07-31,23,135,17,1,36.000000,4116.000000,8.000000
501325,2017-07-31,23,135,21,1,71.000000,12721.000000,18.000000
501326,2017-07-31,23,140,90,1,74.000000,13715.000000,17.000000
501327,2017-07-31,23,144,72,1,65.730000,10999.000000,18.000000
501328,2017-07-31,23,147,33,1,164.000000,27290.000000,54.000000
501329,2017-07-31,23,147,169,1,40.000000,4974.000000,9.000000
501330,2017-07-31,23,149,122,1,96.440000,17186.000000,28.000000
501331,2017-07-31,23,150,74,1,59.000000,9280.000000,18.000000
501332,2017-07-31,23,150,96,1,50.000000,7043.000000,14.000000
501333,2017-07-31,23,150,150,2,43.255000,3968.000000,7.000000
501334,2017-07-31,23,155,3,1,71.910000,6850.000000,13.000000
501335,2017-07-31,23,158,24,1,57.000000,8666.000000,17.000000
501336,2017-07-31,23,167,146,1,61.000000,10784.000000,12.000000
501337,2017-07-31,23,194,8,1,131.000000,24066.000000,28.000000
501338,2017-07-31,23,195,42,1,61.000000,9610.000000,19.000000
501339,2017-07-31,23,223,25,2,57.420000,8828.000000,16.500000
501340,2017-07-31,23,245,175,1,71.000000,12165.000000,21.000000
501341,2017-07-31,23,251,70,1,168.430000,30206.000000,36.000000
501342,2017-07-31,23,360,105,1,34.770000,3749.000000,7.000000
501343,2017-07-31,23,478,80,1,206.000000,37641.000000,35.000000
501344,2017-07-31,23,579,60,1,129.710000,22936.000000,34.000000

In [4]:
test

      test_id create_date  create_hour  start_geo_id  end_geo_id
0           0    2017/8/1           21            24          27
1           1    2017/8/1           21            24           9
2           2    2017/8/1           21            24          22
3           3    2017/8/1           17            24           9
4           4    2017/8/1           17            55          55
5           5    2017/8/1           17           110          88
6           6    2017/8/1            9            23          21
7           7    2017/8/1           21            16          50
8           8    2017/8/1           13             6          24
9           9    2017/8/1           21             6          22
10         10    2017/8/1           17             6           9
11         11    2017/8/1           21            34          90
12         12    2017/8/1            9             1          13
13         13    2017/8/1           21            24          13
14         14    2017/8/1           21            10          10
15         15    2017/8/1           13            48          72
16         16    2017/8/1            7           649         111
17         17    2017/8/1           21            18          22
18         18    2017/8/1           13            15           6
19         19    2017/8/1           17            24          22
20         20    2017/8/1           21             6          24
21         21    2017/8/1           11            24          24
22         22    2017/8/1           13            27          27
23         23    2017/8/1           21            90          50
24         24    2017/8/1           21            24           6
25         25    2017/8/1           15           152          77
26         26    2017/8/1           11           140         103
27         27    2017/8/1           11            22          24
28         28    2017/8/1            9             1          39
29         29    2017/8/1           13            24          55
...       ...         ...          ...           ...         ...
4970     4970    2017/8/7           17           318          61
4971     4971    2017/8/7            9             6         649
4972     4972    2017/8/7           11           266         267
4973     4973    2017/8/7            5           119          31
4974     4974    2017/8/7           15           107          24
4975     4975    2017/8/7           23           266         267
4976     4976    2017/8/7            7            47         459
4977     4977    2017/8/7           23          1282          73
4978     4978    2017/8/7           21           817         193
4979     4979    2017/8/7           15           379         120
4980     4980    2017/8/7            3           459        1285
4981     4981    2017/8/7           21           110         364
4982     4982    2017/8/7           17           107          24
4983     4983    2017/8/7           13             5          26
4984     4984    2017/8/7            5           229          59
4985     4985    2017/8/7            5           292         735
4986     4986    2017/8/7           15            92         327
4987     4987    2017/8/7            9           205         146
4988     4988    2017/8/7           21          1283         323
4989     4989    2017/8/7            1           107          24
4990     4990    2017/8/7           17            79         117
4991     4991    2017/8/7           21           331         837
4992     4992    2017/8/7           19           260         353
4993     4993    2017/8/7           19           228        1013
4994     4994    2017/8/7            1           316         316
4995     4995    2017/8/7           17           354         403
4996     4996    2017/8/7           23           275         264
4997     4997    2017/8/7           15           110         364
4998     4998    2017/8/7           13           817         193
4999     4999    2017/8/7           13            92         327

[5000 rows x 5 columns]

In [5]:
train_aug_demand

      create_date  create_hour  start_geo_id  end_geo_id  demand_count
0      2017-08-01            0             1           1             1
1      2017-08-01            0             1           9             1
2      2017-08-01            0             1          41             1
3      2017-08-01            0             1          73             1
4      2017-08-01            0             1         101             1
5      2017-08-01            0             1         191             1
6      2017-08-01            0             1         198             1
7      2017-08-01            0             3          56             1
8      2017-08-01            0             5           1             1
9      2017-08-01            0             5           5             3
10     2017-08-01            0             5          18             1
11     2017-08-01            0             5          24             1
12     2017-08-01            0             5          55             1
13     2017-08-01            0             5          56             1
14     2017-08-01            0             5          62             1
15     2017-08-01            0             5         107             1
16     2017-08-01            0             5         176             1
17     2017-08-01            0             5         203             1
18     2017-08-01            0             5         211             1
19     2017-08-01            0             5         300             1
20     2017-08-01            0             5         530             1
21     2017-08-01            0             6           9             1
22     2017-08-01            0             6          13             1
23     2017-08-01            0             6          16             2
24     2017-08-01            0             6          39             1
25     2017-08-01            0             6          64             1
26     2017-08-01            0             6          70             1
27     2017-08-01            0             6          80             1
28     2017-08-01            0             6          90             1
29     2017-08-01            0             6          92             1
...           ...          ...           ...         ...           ...
54793  2017-08-07           22           146          63             2
54794  2017-08-07           22           149          27             1
54795  2017-08-07           22           149          72             1
54796  2017-08-07           22           149         149             1
54797  2017-08-07           22           150          21             2
54798  2017-08-07           22           152           6             1
54799  2017-08-07           22           158           1             1
54800  2017-08-07           22           163         110             4
54801  2017-08-07           22           164          33             1
54802  2017-08-07           22           167          47             1
54803  2017-08-07           22           168         298             1
54804  2017-08-07           22           173          88             3
54805  2017-08-07           22           184           4             1
54806  2017-08-07           22           184          24             1
54807  2017-08-07           22           184          87             2
54808  2017-08-07           22           191         243             1
54809  2017-08-07           22           194           9             1
54810  2017-08-07           22           194          27             1
54811  2017-08-07           22           195          18             1
54812  2017-08-07           22           198           1             1
54813  2017-08-07           22           198         160             3
54814  2017-08-07           22           201         127             1
54815  2017-08-07           22           223          49             1
54816  2017-08-07           22           251           5             1
54817  2017-08-07           22           300         306             1
54818  2017-08-07           22           343         932             1
54819  2017-08-07           22           349          60             1
54820  2017-08-07           22           349         472             1
54821  2017-08-07           22           353         223             2
54822  2017-08-07           22           693          10             2

[54823 rows x 5 columns]

In [6]:
test['create_hour'].value_counts()

22    443
20    411
21    383
17    346
13    334
9     313
18    261
15    254
8     246
16    242
11    240
7     234
19    225
10    211
14    201
12    180
23    147
6      76
0      70
1      61
5      47
3      30
2      25
4      20
Name: create_hour, dtype: int64

### Valid set split

In [7]:
# train_aug_exc = train_aug[train_aug['driver_id'] != 2].copy()
train_aug_exc = train_aug.copy()
coord_aug = train_aug_exc.groupby(['create_date','create_hour','start_geo_id','end_geo_id'],as_index=False)['start_geo_id'].agg({'demand_count':'count'})
# coord_aug.to_csv('train_aug_exc.csv',index=False)
coord_aug

      create_date  create_hour  start_geo_id  end_geo_id  demand_count
0      2017-08-01            0             1           1             1
1      2017-08-01            0             1           9             1
2      2017-08-01            0             1          41             1
3      2017-08-01            0             1          73             1
4      2017-08-01            0             1         101             1
5      2017-08-01            0             1         191             1
6      2017-08-01            0             1         198             1
7      2017-08-01            0             3          56             1
8      2017-08-01            0             5           1             1
9      2017-08-01            0             5           5             3
10     2017-08-01            0             5          18             1
11     2017-08-01            0             5          24             1
12     2017-08-01            0             5          55             1
13     2017-08-01            0             5          56             1
14     2017-08-01            0             5          62             1
15     2017-08-01            0             5         107             1
16     2017-08-01            0             5         176             1
17     2017-08-01            0             5         203             1
18     2017-08-01            0             5         211             1
19     2017-08-01            0             5         300             1
20     2017-08-01            0             5         530             1
21     2017-08-01            0             6           9             1
22     2017-08-01            0             6          13             1
23     2017-08-01            0             6          16             2
24     2017-08-01            0             6          39             1
25     2017-08-01            0             6          64             1
26     2017-08-01            0             6          70             1
27     2017-08-01            0             6          80             1
28     2017-08-01            0             6          90             1
29     2017-08-01            0             6          92             1
...           ...          ...           ...         ...           ...
54793  2017-08-07           22           146          63             2
54794  2017-08-07           22           149          27             1
54795  2017-08-07           22           149          72             1
54796  2017-08-07           22           149         149             1
54797  2017-08-07           22           150          21             2
54798  2017-08-07           22           152           6             1
54799  2017-08-07           22           158           1             1
54800  2017-08-07           22           163         110             4
54801  2017-08-07           22           164          33             1
54802  2017-08-07           22           167          47             1
54803  2017-08-07           22           168         298             1
54804  2017-08-07           22           173          88             3
54805  2017-08-07           22           184           4             1
54806  2017-08-07           22           184          24             1
54807  2017-08-07           22           184          87             2
54808  2017-08-07           22           191         243             1
54809  2017-08-07           22           194           9             1
54810  2017-08-07           22           194          27             1
54811  2017-08-07           22           195          18             1
54812  2017-08-07           22           198           1             1
54813  2017-08-07           22           198         160             3
54814  2017-08-07           22           201         127             1
54815  2017-08-07           22           223          49             1
54816  2017-08-07           22           251           5             1
54817  2017-08-07           22           300         306             1
54818  2017-08-07           22           343         932             1
54819  2017-08-07           22           349          60             1
54820  2017-08-07           22           349         472             1
54821  2017-08-07           22           353         223             2
54822  2017-08-07           22           693          10             2

[54823 rows x 5 columns]

In [8]:
dict_list = {
'l_50' : [0,1,2,3,4,5],
'l_100' : [6],
'l_150' : [12,23],
'l_200' : [10,14,19],
'l_250' : [7,8,11,15,16,18],
'l_300' : [9,13],
'l_350' : [17],
'l_400' : [20,21]
# 'l_450' : [22]
}
l_22 = coord_aug[coord_aug['create_hour'] == 22].index
r = np.random.choice(l_22,450)
valid = coord_aug.iloc[r]
for key,l in dict_list.items():
    num =  int(key.split('_')[1])
    for hour in l:
        l_tmp = coord_aug[coord_aug['create_hour'] == hour].index
        r = np.random.choice(l_tmp,num)
        tmp_valid = coord_aug.iloc[r].copy()
        valid = pd.concat([valid,tmp_valid],axis=0)
valid.sort_values(['create_date','create_hour'],inplace=True)
valid

      create_date  create_hour  start_geo_id  end_geo_id  demand_count
277    2017-08-01            0           120          74             1
36     2017-08-01            0             9         109             1
21     2017-08-01            0             6           9             1
125    2017-08-01            0            24          63             1
200    2017-08-01            0            50          56             2
26     2017-08-01            0             6          70             1
170    2017-08-01            0            39          27             1
17     2017-08-01            0             5         203             1
366    2017-08-01            2            55          34             1
337    2017-08-01            2            24          76             1
356    2017-08-01            2            40           2             3
321    2017-08-01            2            19          15             1
339    2017-08-01            2            24          94             1
304    2017-08-01            2             5          39             1
329    2017-08-01            2            24           3             1
380    2017-08-01            2           152          93             1
415    2017-08-01            4            40          60             1
382    2017-08-01            4             3          60             2
394    2017-08-01            4            16          19             1
443    2017-08-01            4           140          47             1
430    2017-08-01            4            70          90             1
401    2017-08-01            4            24          15             1
417    2017-08-01            4            41          16             1
385    2017-08-01            4             6          19             1
416    2017-08-01            4            40          66             2
397    2017-08-01            4            20          19             1
438    2017-08-01            4            88          61             1
805    2017-08-01            6           204          49             1
628    2017-08-01            6            48          41             1
632    2017-08-01            6            48         210             1
...           ...          ...           ...         ...           ...
54244  2017-08-07           22            18           8             2
54330  2017-08-07           22            22          26             3
54644  2017-08-07           22            63         119             1
54121  2017-08-07           22             9           9             5
54647  2017-08-07           22            64           9             1
54068  2017-08-07           22             1         191             1
54663  2017-08-07           22            70          30             1
54643  2017-08-07           22            63         102             1
54800  2017-08-07           22           163         110             4
54434  2017-08-07           22            27          47             1
54506  2017-08-07           22            39          97             2
54253  2017-08-07           22            18          27             1
54568  2017-08-07           22            51         112             1
54792  2017-08-07           22           146           8             1
54382  2017-08-07           22            24          71             3
54207  2017-08-07           22            15          90             1
54603  2017-08-07           22            59          23             1
54543  2017-08-07           22            47          64             1
54155  2017-08-07           22            10          74             1
54561  2017-08-07           22            50          45             1
54542  2017-08-07           22            47          62             1
54497  2017-08-07           22            39          58             1
54377  2017-08-07           22            24          51             1
54774  2017-08-07           22           109          51             1
54097  2017-08-07           22             6          39             2
54532  2017-08-07           22            47          15             1
54718  2017-08-07           22            76          80             1
54130  2017-08-07           22             9          50             1
54730  2017-08-07           22            79           3             1
54514  2017-08-07           22            41          36             1

[5000 rows x 5 columns]

In [9]:
valid['create_hour'].unique()

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22,  1,  3,  5,  7,  9,
       11, 13, 15, 17, 19, 21, 23], dtype=int64)

## Feature Extracting
### 1. order list attribution

In [10]:
train_tr = coord_jul.copy()
valid_tr = valid.copy()
train_tr
# valid_tr
# valid_tr['demand_count']

,create_date,create_hour,start_geo_id,end_geo_id,demand_count,estimate_money_mean,estimate_distance_mean,estimate_term_mean
0,2017-07-01,0,0,10,1,101.000000,14431.000000,24.000000
1,2017-07-01,0,0,21,1,39.000000,4905.000000,9.000000
2,2017-07-01,0,0,64,1,78.860000,8764.000000,9.000000
3,2017-07-01,0,1,1,2,28.500000,2437.000000,4.500000
4,2017-07-01,0,1,15,2,67.000000,10955.000000,21.500000
5,2017-07-01,0,1,37,1,63.000000,10010.000000,20.000000
6,2017-07-01,0,1,39,2,67.110000,11493.000000,17.500000
7,2017-07-01,0,1,89,2,59.675000,9208.500000,18.000000
8,2017-07-01,0,1,95,1,90.000000,15677.000000,31.000000
9,2017-07-01,0,1,160,2,46.520000,6347.000000,12.000000
10,2017-07-01,0,1,303,1,66.000000,11493.000000,17.000000
11,2017-07-01,0,2,2,1,233.000000,36363.000000,36.000000
12,2017-07-01,0,2,5,1,234.290000,36363.000000,37.000000
13,2017-07-01,0,2,38,7,71.901429,6602.714286,13.000000
14,2017-07-01,0,2,46,5,149.892000,17490.200000,22.600000
15,2017-07-01,0,2,265,1,315.000000,41878.000000,49.000000
16,2017-07-01,0,3,80,1,52.000000,4728.000000,9.000000
17,2017-07-01,0,4,97,1,37.000000,4308.000000,8.000000
18,2017-07-01,0,5,0,3,140.083333,20009.000000,18.333333
19,2017-07-01,0,5,1,1,206.000000,27950.000000,33.000000
20,2017-07-01,0,5,8,3,129.566667,19778.666667,21.333333
21,2017-07-01,0,5,9,3,192.633333,26606.000000,27.000000
22,2017-07-01,0,5,18,3,125.733333,17620.000000,20.666667
23,2017-07-01,0,5,22,5,146.710000,20771.800000,19.800000
24,2017-07-01,0,5,29,1,201.000000,27823.000000,28.000000
25,2017-07-01,0,5,30,2,284.135000,37830.000000,45.000000
26,2017-07-01,0,5,31,1,380.000000,36014.000000,35.000000
27,2017-07-01,0,5,34,1,240.000000,32813.000000,34.000000
28,2017-07-01,0,5,39,3,151.160000,23301.333333,23.000000
29,2017-07-01,0,5,51,3,132.980000,18438.333333,22.666667
...,...,...,...,...,...,...,...,...
501315,2017-07-31,23,114,56,1,78.000000,13353.000000,26.000000
501316,2017-07-31,23,114,76,2,82.625000,14957.000000,24.000000
501317,2017-07-31,23,118,25,1,23.000000,1179.000000,2.000000
501318,2017-07-31,23,118,118,1,26.000000,1913.000000,3.000000
501319,2017-07-31,23,118,119,1,45.000000,6389.000000,10.000000
501320,2017-07-31,23,119,44,1,32.000000,3154.000000,6.000000
501321,2017-07-31,23,119,90,1,67.000000,11256.000000,20.000000
501322,2017-07-31,23,124,157,1,53.000000,7900.000000,15.000000
501323,2017-07-31,23,126,108,1,81.180000,14343.000000,25.000000
501324,2017-07-31,23,135,17,1,36.000000,4116.000000,8.000000
501325,2017-07-31,23,135,21,1,71.000000,12721.000000,18.000000
501326,2017-07-31,23,140,90,1,74.000000,13715.000000,17.000000
501327,2017-07-31,23,144,72,1,65.730000,10999.000000,18.000000
501328,2017-07-31,23,147,33,1,164.000000,27290.000000,54.000000
501329,2017-07-31,23,147,169,1,40.000000,4974.000000,9.000000
501330,2017-07-31,23,149,122,1,96.440000,17186.000000,28.000000
501331,2017-07-31,23,150,74,1,59.000000,9280.000000,18.000000
501332,2017-07-31,23,150,96,1,50.000000,7043.000000,14.000000
501333,2017-07-31,23,150,150,2,43.255000,3968.000000,7.000000
501334,2017-07-31,23,155,3,1,71.910000,6850.000000,13.000000
501335,2017-07-31,23,158,24,1,57.000000,8666.000000,17.000000
501336,2017-07-31,23,167,146,1,61.000000,10784.000000,12.000000
501337,2017-07-31,23,194,8,1,131.000000,24066.000000,28.000000
501338,2017-07-31,23,195,42,1,61.000000,9610.000000,19.000000
501339,2017-07-31,23,223,25,2,57.420000,8828.000000,16.500000
501340,2017-07-31,23,245,175,1,71.000000,12165.000000,21.000000
501341,2017-07-31,23,251,70,1,168.430000,30206.000000,36.000000
501342,2017-07-31,23,360,105,1,34.770000,3749.000000,7.000000
501343,2017-07-31,23,478,80,1,206.000000,37641.000000,35.000000
501344,2017-07-31,23,579,60,1,129.710000,22936.000000,34.000000

In [11]:
# time attribution
holiday['create_date'] = pd.to_datetime(holiday['create_date'])
train_tr['create_date'] = pd.to_datetime(train_tr['create_date'])
valid_tr['create_date'] = pd.to_datetime(valid_tr['create_date'])
train_tr = pd.merge(train_tr,holiday,on='create_date',how='left')
valid_tr = pd.merge(valid_tr,holiday,on='create_date',how='left')
train_tr['dayOfWeek'] = train_tr['create_date'].dt.dayofweek
valid_tr['dayOfWeek'] = valid_tr['create_date'].dt.dayofweek
train_tr

# # time attribution
# holiday['create_date'] = pd.to_datetime(holiday['create_date'])
# train_tr['create_date'] = pd.to_datetime(train_tr['create_date'])
# test['create_date'] = pd.to_datetime(test['create_date'])
# train_tr = pd.merge(train_tr,holiday,on='create_date',how='left')
# test = pd.merge(test,holiday,on='create_date',how='left')
# train_tr['dayOfWeek'] = train_tr['create_date'].dt.dayofweek
# test['dayOfWeek'] = test['create_date'].dt.dayofweek
# test

,create_date,create_hour,start_geo_id,end_geo_id,demand_count,estimate_money_mean,estimate_distance_mean,estimate_term_mean,holiday,dayOfWeek
0,2017-07-01,0,0,10,1,101.000000,14431.000000,24.000000,1,5
1,2017-07-01,0,0,21,1,39.000000,4905.000000,9.000000,1,5
2,2017-07-01,0,0,64,1,78.860000,8764.000000,9.000000,1,5
3,2017-07-01,0,1,1,2,28.500000,2437.000000,4.500000,1,5
4,2017-07-01,0,1,15,2,67.000000,10955.000000,21.500000,1,5
5,2017-07-01,0,1,37,1,63.000000,10010.000000,20.000000,1,5
6,2017-07-01,0,1,39,2,67.110000,11493.000000,17.500000,1,5
7,2017-07-01,0,1,89,2,59.675000,9208.500000,18.000000,1,5
8,2017-07-01,0,1,95,1,90.000000,15677.000000,31.000000,1,5
9,2017-07-01,0,1,160,2,46.520000,6347.000000,12.000000,1,5
10,2017-07-01,0,1,303,1,66.000000,11493.000000,17.000000,1,5
11,2017-07-01,0,2,2,1,233.000000,36363.000000,36.000000,1,5
12,2017-07-01,0,2,5,1,234.290000,36363.000000,37.000000,1,5
13,2017-07-01,0,2,38,7,71.901429,6602.714286,13.000000,1,5
14,2017-07-01,0,2,46,5,149.892000,17490.200000,22.600000,1,5
15,2017-07-01,0,2,265,1,315.000000,41878.000000,49.000000,1,5
16,2017-07-01,0,3,80,1,52.000000,4728.000000,9.000000,1,5
17,2017-07-01,0,4,97,1,37.000000,4308.000000,8.000000,1,5
18,2017-07-01,0,5,0,3,140.083333,20009.000000,18.333333,1,5
19,2017-07-01,0,5,1,1,206.000000,27950.000000,33.000000,1,5
20,2017-07-01,0,5,8,3,129.566667,19778.666667,21.333333,1,5
21,2017-07-01,0,5,9,3,192.633333,26606.000000,27.000000,1,5
22,2017-07-01,0,5,18,3,125.733333,17620.000000,20.666667,1,5
23,2017-07-01,0,5,22,5,146.710000,20771.800000,19.800000,1,5
24,2017-07-01,0,5,29,1,201.000000,27823.000000,28.000000,1,5
25,2017-07-01,0,5,30,2,284.135000,37830.000000,45.000000,1,5
26,2017-07-01,0,5,31,1,380.000000,36014.000000,35.000000,1,5
27,2017-07-01,0,5,34,1,240.000000,32813.000000,34.000000,1,5
28,2017-07-01,0,5,39,3,151.160000,23301.333333,23.000000,1,5
29,2017-07-01,0,5,51,3,132.980000,18438.333333,22.666667,1,5
...,...,...,...,...,...,...,...,...,...,...
501315,2017-07-31,23,114,56,1,78.000000,13353.000000,26.000000,0,0
501316,2017-07-31,23,114,76,2,82.625000,14957.000000,24.000000,0,0
501317,2017-07-31,23,118,25,1,23.000000,1179.000000,2.000000,0,0
501318,2017-07-31,23,118,118,1,26.000000,1913.000000,3.000000,0,0
501319,2017-07-31,23,118,119,1,45.000000,6389.000000,10.000000,0,0
501320,2017-07-31,23,119,44,1,32.000000,3154.000000,6.000000,0,0
501321,2017-07-31,23,119,90,1,67.000000,11256.000000,20.000000,0,0
501322,2017-07-31,23,124,157,1,53.000000,7900.000000,15.000000,0,0
501323,2017-07-31,23,126,108,1,81.180000,14343.000000,25.000000,0,0
501324,2017-07-31,23,135,17,1,36.000000,4116.000000,8.000000,0,0
501325,2017-07-31,23,135,21,1,71.000000,12721.000000,18.000000,0,0
501326,2017-07-31,23,140,90,1,74.000000,13715.000000,17.000000,0,0
501327,2017-07-31,23,144,72,1,65.730000,10999.000000,18.000000,0,0
501328,2017-07-31,23,147,33,1,164.000000,27290.000000,54.000000,0,0
501329,2017-07-31,23,147,169,1,40.000000,4974.000000,9.000000,0,0
501330,2017-07-31,23,149,122,1,96.440000,17186.000000,28.000000,0,0
501331,2017-07-31,23,150,74,1,59.000000,9280.000000,18.000000,0,0
501332,2017-07-31,23,150,96,1,50.000000,7043.000000,14.000000,0,0
501333,2017-07-31,23,150,150,2,43.255000,3968.000000,7.000000,0,0
501334,2017-07-31,23,155,3,1,71.910000,6850.000000,13.000000,0,0
501335,2017-07-31,23,158,24,1,57.000000,8666.000000,17.000000,0,0
501336,2017-07-31,23,167,146,1,61.000000,10784.000000,12.000000,0,0
501337,2017-07-31,23,194,8,1,131.000000,24066.000000,28.000000,0,0
501338,2017-07-31,23,195,42,1,61.000000,9610.000000,19.000000,0,0
501339,2017-07-31,23,223,25,2,57.420000,8828.000000,16.500000,0,0
501340,2017-07-31,23,245,175,1,71.000000,12165.000000,21.000000,0,0
501341,2017-07-31,23,251,70,1,168.430000,30206.000000,36.000000,0,0
501342,2017-07-31,23,360,105,1,34.770000,3749.000000,7.000000,0,0
501343,2017-07-31,23,478,80,1,206.000000,37641.000000,35.000000,0,0
501344,2017-07-31,23,579,60,1,129.710000,22936.000000,34.000000,0,0

In [12]:
coord_money_hour = train_tr.groupby(['create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_money_mean'].agg({'money_hour_mean':'mean'})
coord_money_day = train_tr.groupby(['dayOfWeek','start_geo_id','end_geo_id'],as_index=False)['estimate_money_mean'].agg({'money_day_mean':'mean'})
coord_dis_hour = train_tr.groupby(['start_geo_id','end_geo_id'],as_index=False)['estimate_distance_mean'].agg({'dis_hour_mean':'mean'})
coord_term_hour = train_tr.groupby(['start_geo_id','end_geo_id'],as_index=False)['estimate_term_mean'].agg({'term_hour_mean':'mean'})
train_tr = pd.merge(train_tr,coord_money_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
train_tr = pd.merge(train_tr,coord_money_day,on=['dayOfWeek','start_geo_id','end_geo_id'],how='left')
train_tr = pd.merge(train_tr,coord_dis_hour,on=['start_geo_id','end_geo_id'],how='left')
train_tr = pd.merge(train_tr,coord_term_hour,on=['start_geo_id','end_geo_id'],how='left')
valid_tr = pd.merge(valid_tr,coord_money_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
valid_tr = pd.merge(valid_tr,coord_money_day,on=['dayOfWeek','start_geo_id','end_geo_id'],how='left')
valid_tr = pd.merge(valid_tr,coord_dis_hour,on=['start_geo_id','end_geo_id'],how='left')
valid_tr = pd.merge(valid_tr,coord_term_hour,on=['start_geo_id','end_geo_id'],how='left')
valid_tr

# coord_money_hour = train_tr.groupby(['create_hour','start_geo_id','end_geo_id'],as_index=False)['estimate_money_mean'].agg({'money_hour_mean':'mean'})
# coord_money_day = train_tr.groupby(['dayOfWeek','start_geo_id','end_geo_id'],as_index=False)['estimate_money_mean'].agg({'money_day_mean':'mean'})
# coord_dis_hour = train_tr.groupby(['start_geo_id','end_geo_id'],as_index=False)['estimate_distance_mean'].agg({'dis_hour_mean':'mean'})
# coord_term_hour = train_tr.groupby(['start_geo_id','end_geo_id'],as_index=False)['estimate_term_mean'].agg({'term_hour_mean':'mean'})
# train_tr = pd.merge(train_tr,coord_money_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
# # train_tr = pd.merge(train_tr,coord_money_day,on=['dayOfWeek','start_geo_id','end_geo_id'],how='left')
# train_tr = pd.merge(train_tr,coord_dis_hour,on=['start_geo_id','end_geo_id'],how='left')
# train_tr = pd.merge(train_tr,coord_term_hour,on=['start_geo_id','end_geo_id'],how='left')
# test = pd.merge(test,coord_money_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
# test = pd.merge(test,coord_money_day,on=['dayOfWeek','start_geo_id','end_geo_id'],how='left')
# test = pd.merge(test,coord_dis_hour,on=['start_geo_id','end_geo_id'],how='left')
# test = pd.merge(test,coord_term_hour,on=['start_geo_id','end_geo_id'],how='left')
# test

,create_date,create_hour,start_geo_id,end_geo_id,demand_count,holiday,dayOfWeek,money_hour_mean,money_day_mean,dis_hour_mean,term_hour_mean
0,2017-08-01,0,120,74,1,0,1,NaN,NaN,NaN,NaN
1,2017-08-01,0,9,109,1,0,1,78.272500,73.178333,11969.869863,22.707763
2,2017-08-01,0,6,9,1,0,1,48.440833,52.794470,6517.478098,12.455708
3,2017-08-01,0,24,63,1,0,1,73.226375,72.096218,11121.082444,20.352884
4,2017-08-01,0,50,56,2,0,1,61.873333,54.676749,7830.344607,14.830501
5,2017-08-01,0,6,70,1,0,1,85.500000,78.928470,12052.027640,22.649456
6,2017-08-01,0,39,27,1,0,1,58.318755,54.224607,6883.846827,12.804181
7,2017-08-01,0,5,203,1,0,1,133.000000,113.000000,24493.875000,30.000000
8,2017-08-01,2,55,34,1,0,1,39.535000,41.284687,4538.260249,8.490755
9,2017-08-01,2,24,76,1,0,1,45.492000,56.442873,7465.948594,14.329185
10,2017-08-01,2,40,2,3,0,1,NaN,48.000000,8371.428571,16.285714
11,2017-08-01,2,19,15,1,0,1,NaN,38.156236,3958.064338,7.422860
12,2017-08-01,2,24,94,1,0,1,69.163333,80.405812,11280.897349,21.704221
13,2017-08-01,2,5,39,1,0,1,141.000000,118.014306,23972.281532,31.873311
14,2017-08-01,2,24,3,1,0,1,51.347000,51.162467,7051.912512,13.304600
15,2017-08-01,2,152,93,1,0,1,NaN,NaN,NaN,NaN
16,2017-08-01,4,40,60,1,0,1,214.625000,226.500000,38126.730769,53.942308
17,2017-08-01,4,3,60,2,0,1,163.570000,206.104167,29715.693333,43.199667
18,2017-08-01,4,16,19,1,0,1,35.875000,38.002339,4366.878105,8.212042
19,2017-08-01,4,140,47,1,0,1,NaN,NaN,53841.333333,66.000000
20,2017-08-01,4,70,90,1,0,1,NaN,51.846270,6606.354600,11.829968
21,2017-08-01,4,24,15,1,0,1,45.837500,50.432996,5808.238490,11.098897
22,2017-08-01,4,41,16,1,0,1,NaN,47.591049,5671.137401,10.757265
23,2017-08-01,4,6,19,1,0,1,33.223333,37.907110,3860.959904,7.189842
24,2017-08-01,4,40,66,2,0,1,NaN,30.786667,6000.888889,11.333333
25,2017-08-01,4,20,19,1,0,1,71.500000,80.748958,10894.901235,21.288066
26,2017-08-01,4,88,61,1,0,1,NaN,38.409469,4113.891006,7.577098
27,2017-08-01,6,204,49,1,0,1,31.470833,39.682143,3628.806818,6.545455
28,2017-08-01,6,48,41,1,0,1,35.207750,40.654409,4086.465201,7.668960
29,2017-08-01,6,48,210,1,0,1,78.000000,89.773333,16366.428571,27.714286
...,...,...,...,...,...,...,...,...,...,...,...
4970,2017-08-07,22,18,8,2,0,0,40.815177,32.717444,4122.597445,7.777719
4971,2017-08-07,22,22,26,3,0,0,44.819637,34.871271,3875.855367,7.191783
4972,2017-08-07,22,63,119,1,0,0,91.000000,111.077143,16005.428571,27.285714
4973,2017-08-07,22,9,9,5,0,0,33.939605,28.677733,2513.793081,4.478060
4974,2017-08-07,22,64,9,1,0,0,110.745000,73.190962,13175.305708,24.874201
4975,2017-08-07,22,1,191,1,0,0,115.720000,70.500000,16374.994253,30.390805
4976,2017-08-07,22,70,30,1,0,0,76.616667,62.298750,9048.963768,17.076087
4977,2017-08-07,22,63,102,1,0,0,66.000000,50.980625,6957.944444,13.166667
4978,2017-08-07,22,163,110,4,0,0,NaN,NaN,NaN,NaN
4979,2017-08-07,22,27,47,1,0,0,206.170000,171.635933,31070.817342,45.931081
4980,2017-08-07,22,39,97,2,0,0,168.235000,128.000000,21119.526316,39.631579
4981,2017-08-07,22,18,27,1,0,0,91.040573,70.852205,12465.087046,23.868510
4982,2017-08-07,22,51,112,1,0,0,NaN,71.000000,10761.833333,20.000000
4983,2017-08-07,22,146,8,1,0,0,NaN,88.500000,10705.333333,20.333333
4984,2017-08-07,22,24,71,3,0,0,104.160361,83.262439,14373.561129,25.571616
4985,2017-08-07,22,15,90,1,0,0,98.231639,78.945000,13062.195013,25.248546
4986,2017-08-07,22,59,23,1,0,0,59.000000,NaN,13498.500000,25.500000
4987,2017-08-07,22,47,64,1,0,0,122.734167,129.450417,26118.223770,33.992897
4988,2017-08-07,22,10,74,1,0,0,95.411667,81.709630,14011.948496,26.351253
4989,2017-08-07,22,50,45,1,0,0,54.000000,46.800444,6540.953795,12.051155
4990,2017-08-07,22,47,62,1,0,0,163.782857,187.806364,35109.272989,50.929310
4991,2017-08-07,22,39,58,1,0,0,NaN,150.500000,21903.765432,41.981481
4992,2017-08-07,22,24,51,1,0,0,85.216645,69.174595,11887.392869,21.634554
4993,2017-08-07,22,109,51,1,0,0,85.560000,113.230000,18766.500000,31.500000
4994,2017-08-07,22,6,39,2,0,0,50.484988,36.475926,4335.987689,8.090178
4995,2017-08-07,22,47,15,1,0,0,189.613333,150.662857,29000.214815,43.341077
4996,2017-08-07,22,76,80,1,0,0,90.002500,88.083125,12831.155172,23.224138
4997,2017-08-07,22,9,50,1,0,0,94.000000,91.948750,17384.134058,33.750000
4998,2017-08-07,22,79,3,1,0,0,35.405000,31.130130,3573.483168,6.630854
4999,2017-08-07,22,41,36,1,0,0,NaN,109.000000,22413.071429,41.535714

### 2.Location
#### 2.1 Pure location

In [13]:
loc_start = loc_cls.copy()
loc_start.rename(columns={'location_id':'start_geo_id','cluster':'start_cluster'},inplace=True)
train_tr = pd.merge(train_tr,loc_start,on='start_geo_id',how='left')
loc_end = loc_cls.copy()
loc_end.rename(columns={'location_id':'end_geo_id','cluster':'end_cluster'},inplace=True)
train_tr = pd.merge(train_tr,loc_end,on='end_geo_id',how='left')
loc_start = loc_cls.copy()
loc_start.rename(columns={'location_id':'start_geo_id','cluster':'start_cluster'},inplace=True)
valid_tr = pd.merge(valid_tr,loc_start,on='start_geo_id',how='left')
loc_end = loc_cls.copy()
loc_end.rename(columns={'location_id':'end_geo_id','cluster':'end_cluster'},inplace=True)
valid_tr = pd.merge(valid_tr,loc_end,on='end_geo_id',how='left')
# valid_tr['end_cluster'].astype('int',inplace=True)
valid_tr

# loc_start = loc_cls.copy()
# loc_start.rename(columns={'location_id':'start_geo_id','cluster':'start_cluster'},inplace=True)
# train_tr = pd.merge(train_tr,loc_start,on='start_geo_id',how='left')
# loc_end = loc_cls.copy()
# loc_end.rename(columns={'location_id':'end_geo_id','cluster':'end_cluster'},inplace=True)
# train_tr = pd.merge(train_tr,loc_end,on='end_geo_id',how='left')
# loc_start = loc_cls.copy()
# loc_start.rename(columns={'location_id':'start_geo_id','cluster':'start_cluster'},inplace=True)
# test = pd.merge(test,loc_start,on='start_geo_id',how='left')
# loc_end = loc_cls.copy()
# loc_end.rename(columns={'location_id':'end_geo_id','cluster':'end_cluster'},inplace=True)
# test = pd.merge(test,loc_end,on='end_geo_id',how='left')
# # test['end_cluster'].astype('int',inplace=True)
# test

,create_date,create_hour,start_geo_id,end_geo_id,demand_count,holiday,dayOfWeek,money_hour_mean,money_day_mean,dis_hour_mean,term_hour_mean,start_cluster,end_cluster
0,2017-08-01,0,120,74,1,0,1,NaN,NaN,NaN,NaN,5.0,1.0
1,2017-08-01,0,9,109,1,0,1,78.272500,73.178333,11969.869863,22.707763,5.0,1.0
2,2017-08-01,0,6,9,1,0,1,48.440833,52.794470,6517.478098,12.455708,5.0,5.0
3,2017-08-01,0,24,63,1,0,1,73.226375,72.096218,11121.082444,20.352884,1.0,5.0
4,2017-08-01,0,50,56,2,0,1,61.873333,54.676749,7830.344607,14.830501,1.0,5.0
5,2017-08-01,0,6,70,1,0,1,85.500000,78.928470,12052.027640,22.649456,5.0,5.0
6,2017-08-01,0,39,27,1,0,1,58.318755,54.224607,6883.846827,12.804181,1.0,5.0
7,2017-08-01,0,5,203,1,0,1,133.000000,113.000000,24493.875000,30.000000,4.0,4.0
8,2017-08-01,2,55,34,1,0,1,39.535000,41.284687,4538.260249,8.490755,1.0,1.0
9,2017-08-01,2,24,76,1,0,1,45.492000,56.442873,7465.948594,14.329185,1.0,5.0
10,2017-08-01,2,40,2,3,0,1,NaN,48.000000,8371.428571,16.285714,3.0,1.0
11,2017-08-01,2,19,15,1,0,1,NaN,38.156236,3958.064338,7.422860,5.0,1.0
12,2017-08-01,2,24,94,1,0,1,69.163333,80.405812,11280.897349,21.704221,1.0,1.0
13,2017-08-01,2,5,39,1,0,1,141.000000,118.014306,23972.281532,31.873311,4.0,1.0
14,2017-08-01,2,24,3,1,0,1,51.347000,51.162467,7051.912512,13.304600,1.0,5.0
15,2017-08-01,2,152,93,1,0,1,NaN,NaN,NaN,NaN,0.0,0.0
16,2017-08-01,4,40,60,1,0,1,214.625000,226.500000,38126.730769,53.942308,3.0,4.0
17,2017-08-01,4,3,60,2,0,1,163.570000,206.104167,29715.693333,43.199667,5.0,4.0
18,2017-08-01,4,16,19,1,0,1,35.875000,38.002339,4366.878105,8.212042,5.0,5.0
19,2017-08-01,4,140,47,1,0,1,NaN,NaN,53841.333333,66.000000,1.0,2.0
20,2017-08-01,4,70,90,1,0,1,NaN,51.846270,6606.354600,11.829968,5.0,5.0
21,2017-08-01,4,24,15,1,0,1,45.837500,50.432996,5808.238490,11.098897,1.0,1.0
22,2017-08-01,4,41,16,1,0,1,NaN,47.591049,5671.137401,10.757265,5.0,5.0
23,2017-08-01,4,6,19,1,0,1,33.223333,37.907110,3860.959904,7.189842,5.0,5.0
24,2017-08-01,4,40,66,2,0,1,NaN,30.786667,6000.888889,11.333333,3.0,0.0
25,2017-08-01,4,20,19,1,0,1,71.500000,80.748958,10894.901235,21.288066,5.0,5.0
26,2017-08-01,4,88,61,1,0,1,NaN,38.409469,4113.891006,7.577098,5.0,5.0
27,2017-08-01,6,204,49,1,0,1,31.470833,39.682143,3628.806818,6.545455,0.0,5.0
28,2017-08-01,6,48,41,1,0,1,35.207750,40.654409,4086.465201,7.668960,5.0,5.0
29,2017-08-01,6,48,210,1,0,1,78.000000,89.773333,16366.428571,27.714286,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4970,2017-08-07,22,18,8,2,0,0,40.815177,32.717444,4122.597445,7.777719,5.0,0.0
4971,2017-08-07,22,22,26,3,0,0,44.819637,34.871271,3875.855367,7.191783,5.0,5.0
4972,2017-08-07,22,63,119,1,0,0,91.000000,111.077143,16005.428571,27.285714,5.0,2.0
4973,2017-08-07,22,9,9,5,0,0,33.939605,28.677733,2513.793081,4.478060,5.0,5.0
4974,2017-08-07,22,64,9,1,0,0,110.745000,73.190962,13175.305708,24.874201,5.0,5.0
4975,2017-08-07,22,1,191,1,0,0,115.720000,70.500000,16374.994253,30.390805,1.0,5.0
4976,2017-08-07,22,70,30,1,0,0,76.616667,62.298750,9048.963768,17.076087,5.0,1.0
4977,2017-08-07,22,63,102,1,0,0,66.000000,50.980625,6957.944444,13.166667,5.0,0.0
4978,2017-08-07,22,163,110,4,0,0,NaN,NaN,NaN,NaN,0.0,0.0
4979,2017-08-07,22,27,47,1,0,0,206.170000,171.635933,31070.817342,45.931081,5.0,2.0
4980,2017-08-07,22,39,97,2,0,0,168.235000,128.000000,21119.526316,39.631579,1.0,2.0
4981,2017-08-07,22,18,27,1,0,0,91.040573,70.852205,12465.087046,23.868510,5.0,5.0
4982,2017-08-07,22,51,112,1,0,0,NaN,71.000000,10761.833333,20.000000,1.0,0.0
4983,2017-08-07,22,146,8,1,0,0,NaN,88.500000,10705.333333,20.333333,0.0,0.0
4984,2017-08-07,22,24,71,3,0,0,104.160361,83.262439,14373.561129,25.571616,1.0,5.0
4985,2017-08-07,22,15,90,1,0,0,98.231639,78.945000,13062.195013,25.248546,1.0,5.0
4986,2017-08-07,22,59,23,1,0,0,59.000000,NaN,13498.500000,25.500000,1.0,5.0
4987,2017-08-07,22,47,64,1,0,0,122.734167,129.450417,26118.223770,33.992897,2.0,5.0
4988,2017-08-07,22,10,74,1,0,0,95.411667,81.709630,14011.948496,26.351253,5.0,1.0
4989,2017-08-07,22,50,45,1,0,0,54.000000,46.800444,6540.953795,12.051155,1.0,5.0
4990,2017-08-07,22,47,62,1,0,0,163.782857,187.806364,35109.272989,50.929310,2.0,5.0
4991,2017-08-07,22,39,58,1,0,0,NaN,150.500000,21903.765432,41.981481,1.0,2.0
4992,2017-08-07,22,24,51,1,0,0,85.216645,69.174595,11887.392869,21.634554,1.0,1.0
4993,2017-08-07,22,109,51,1,0,0,85.560000,113.230000,18766.500000,31.500000,1.0,1.0
4994,2017-08-07,22,6,39,2,0,0,50.484988,36.475926,4335.987689,8.090178,5.0,1.0
4995,2017-08-07,22,47,15,1,0,0,189.613333,150.662857,29000.214815,43.341077,2.0,1.0
4996,2017-08-07,22,76,80,1,0,0,90.002500,88.083125,12831.155172,23.224138,5.0,5.0
4997,2017-08-07,22,9,50,1,0,0,94.000000,91.948750,17384.134058,33.750000,5.0,1.0
4998,2017-08-07,22,79,3,1,0,0,35.405000,31.130130,3573.483168,6.630854,5.0,5.0
4999,2017-08-07,22,41,36,1,0,0,NaN,109.000000,22413.071429,41.535714,5.0,2.0

In [14]:
coord_se_mean = train_tr.groupby(['start_geo_id','end_geo_id'],as_index=False)['demand_count'].agg({'sloc_eloc_mean':'mean'})
coord_se_median = train_tr.groupby(['start_geo_id','end_geo_id'],as_index=False)['demand_count'].agg({'sloc_eloc_median':'median'})
coord_se_max = train_tr.groupby(['start_geo_id','end_geo_id'],as_index=False)['demand_count'].agg({'sloc_eloc_max':'max'})
coord_se_min = train_tr.groupby(['start_geo_id','end_geo_id'],as_index=False)['demand_count'].agg({'sloc_eloc_min':'min'})
train_tr = pd.merge(train_tr,coord_se_mean,on=['start_geo_id','end_geo_id'],how='left')
train_tr = pd.merge(train_tr,coord_se_median,on=['start_geo_id','end_geo_id'],how='left')
train_tr = pd.merge(train_tr,coord_se_max,on=['start_geo_id','end_geo_id'],how='left')
train_tr = pd.merge(train_tr,coord_se_min,on=['start_geo_id','end_geo_id'],how='left')
valid_tr = pd.merge(valid_tr,coord_se_mean,on=['start_geo_id','end_geo_id'],how='left')
valid_tr = pd.merge(valid_tr,coord_se_median,on=['start_geo_id','end_geo_id'],how='left')
valid_tr = pd.merge(valid_tr,coord_se_max,on=['start_geo_id','end_geo_id'],how='left')
valid_tr = pd.merge(valid_tr,coord_se_min,on=['start_geo_id','end_geo_id'],how='left')
valid_tr

# coord_se_mean = train_tr.groupby(['start_geo_id','end_geo_id'],as_index=False)['demand_count'].agg({'sloc_eloc_mean':'mean'})
# coord_se_median = train_tr.groupby(['start_geo_id','end_geo_id'],as_index=False)['demand_count'].agg({'sloc_eloc_median':'median'})
# coord_se_max = train_tr.groupby(['start_geo_id','end_geo_id'],as_index=False)['demand_count'].agg({'sloc_eloc_max':'max'})
# coord_se_min = train_tr.groupby(['start_geo_id','end_geo_id'],as_index=False)['demand_count'].agg({'sloc_eloc_min':'min'})
# train_tr = pd.merge(train_tr,coord_se_mean,on=['start_geo_id','end_geo_id'],how='left')
# train_tr = pd.merge(train_tr,coord_se_median,on=['start_geo_id','end_geo_id'],how='left')
# train_tr = pd.merge(train_tr,coord_se_max,on=['start_geo_id','end_geo_id'],how='left')
# train_tr = pd.merge(train_tr,coord_se_min,on=['start_geo_id','end_geo_id'],how='left')
# test = pd.merge(test,coord_se_mean,on=['start_geo_id','end_geo_id'],how='left')
# test = pd.merge(test,coord_se_median,on=['start_geo_id','end_geo_id'],how='left')
# test = pd.merge(test,coord_se_max,on=['start_geo_id','end_geo_id'],how='left')
# test = pd.merge(test,coord_se_min,on=['start_geo_id','end_geo_id'],how='left')
# test

,create_date,create_hour,start_geo_id,end_geo_id,demand_count,holiday,dayOfWeek,money_hour_mean,money_day_mean,dis_hour_mean,term_hour_mean,start_cluster,end_cluster,sloc_eloc_mean,sloc_eloc_median,sloc_eloc_max,sloc_eloc_min
0,2017-08-01,0,120,74,1,0,1,NaN,NaN,NaN,NaN,5.0,1.0,NaN,NaN,NaN,NaN
1,2017-08-01,0,9,109,1,0,1,78.272500,73.178333,11969.869863,22.707763,5.0,1.0,1.232877,1.0,3.0,1.0
2,2017-08-01,0,6,9,1,0,1,48.440833,52.794470,6517.478098,12.455708,5.0,5.0,3.256410,2.0,33.0,1.0
3,2017-08-01,0,24,63,1,0,1,73.226375,72.096218,11121.082444,20.352884,1.0,5.0,2.173585,1.0,17.0,1.0
4,2017-08-01,0,50,56,2,0,1,61.873333,54.676749,7830.344607,14.830501,1.0,5.0,1.638418,1.0,13.0,1.0
5,2017-08-01,0,6,70,1,0,1,85.500000,78.928470,12052.027640,22.649456,5.0,5.0,1.792079,1.0,18.0,1.0
6,2017-08-01,0,39,27,1,0,1,58.318755,54.224607,6883.846827,12.804181,1.0,5.0,2.672000,2.0,24.0,1.0
7,2017-08-01,0,5,203,1,0,1,133.000000,113.000000,24493.875000,30.000000,4.0,4.0,1.000000,1.0,1.0,1.0
8,2017-08-01,2,55,34,1,0,1,39.535000,41.284687,4538.260249,8.490755,1.0,1.0,2.835227,2.0,23.0,1.0
9,2017-08-01,2,24,76,1,0,1,45.492000,56.442873,7465.948594,14.329185,1.0,5.0,2.222930,1.0,17.0,1.0
10,2017-08-01,2,40,2,3,0,1,NaN,48.000000,8371.428571,16.285714,3.0,1.0,1.214286,1.0,3.0,1.0
11,2017-08-01,2,19,15,1,0,1,NaN,38.156236,3958.064338,7.422860,5.0,1.0,2.049724,2.0,16.0,1.0
12,2017-08-01,2,24,94,1,0,1,69.163333,80.405812,11280.897349,21.704221,1.0,1.0,2.255814,1.0,23.0,1.0
13,2017-08-01,2,5,39,1,0,1,141.000000,118.014306,23972.281532,31.873311,4.0,1.0,1.256757,1.0,4.0,1.0
14,2017-08-01,2,24,3,1,0,1,51.347000,51.162467,7051.912512,13.304600,1.0,5.0,2.868132,2.0,51.0,1.0
15,2017-08-01,2,152,93,1,0,1,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
16,2017-08-01,4,40,60,1,0,1,214.625000,226.500000,38126.730769,53.942308,3.0,4.0,1.461538,1.0,4.0,1.0
17,2017-08-01,4,3,60,2,0,1,163.570000,206.104167,29715.693333,43.199667,5.0,4.0,1.500000,1.0,6.0,1.0
18,2017-08-01,4,16,19,1,0,1,35.875000,38.002339,4366.878105,8.212042,5.0,5.0,2.330189,1.0,20.0,1.0
19,2017-08-01,4,140,47,1,0,1,NaN,NaN,53841.333333,66.000000,1.0,2.0,1.000000,1.0,1.0,1.0
20,2017-08-01,4,70,90,1,0,1,NaN,51.846270,6606.354600,11.829968,5.0,5.0,1.586420,1.0,10.0,1.0
21,2017-08-01,4,24,15,1,0,1,45.837500,50.432996,5808.238490,11.098897,1.0,1.0,2.612195,2.0,18.0,1.0
22,2017-08-01,4,41,16,1,0,1,NaN,47.591049,5671.137401,10.757265,5.0,5.0,2.096085,1.0,29.0,1.0
23,2017-08-01,4,6,19,1,0,1,33.223333,37.907110,3860.959904,7.189842,5.0,5.0,2.802632,2.0,40.0,1.0
24,2017-08-01,4,40,66,2,0,1,NaN,30.786667,6000.888889,11.333333,3.0,0.0,1.000000,1.0,1.0,1.0
25,2017-08-01,4,20,19,1,0,1,71.500000,80.748958,10894.901235,21.288066,5.0,5.0,1.518519,1.0,6.0,1.0
26,2017-08-01,4,88,61,1,0,1,NaN,38.409469,4113.891006,7.577098,5.0,5.0,2.150442,1.0,15.0,1.0
27,2017-08-01,6,204,49,1,0,1,31.470833,39.682143,3628.806818,6.545455,0.0,5.0,1.227273,1.0,3.0,1.0
28,2017-08-01,6,48,41,1,0,1,35.207750,40.654409,4086.465201,7.668960,5.0,5.0,1.578723,1.0,18.0,1.0
29,2017-08-01,6,48,210,1,0,1,78.000000,89.773333,16366.428571,27.714286,5.0,4.0,1.285714,1.0,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4970,2017-08-07,22,18,8,2,0,0,40.815177,32.717444,4122.597445,7.777719,5.0,0.0,1.825545,1.0,12.0,1.0
4971,2017-08-07,22,22,26,3,0,0,44.819637,34.871271,3875.855367,7.191783,5.0,5.0,2.698297,2.0,40.0,1.0
4972,2017-08-07,22,63,119,1,0,0,91.000000,111.077143,16005.428571,27.285714,5.0,2.0,1.857143,1.0,7.0,1.0
4973,2017-08-07,22,9,9,5,0,0,33.939605,28.677733,2513.793081,4.478060,5.0,5.0,3.884146,3.0,70.0,1.0
4974,2017-08-07,22,64,9,1,0,0,110.745000,73.190962,13175.305708,24.874201,5.0,5.0,1.383562,1.0,6.0,1.0
4975,2017-08-07,22,1,191,1,0,0,115.720000,70.500000,16374.994253,30.390805,1.0,5.0,1.344828,1.0,3.0,1.0
4976,2017-08-07,22,70,30,1,0,0,76.616667,62.298750,9048.963768,17.076087,5.0,1.0,1.456522,1.0,6.0,1.0
4977,2017-08-07,22,63,102,1,0,0,66.000000,50.980625,6957.944444,13.166667,5.0,0.0,1.233333,1.0,3.0,1.0
4978,2017-08-07,22,163,110,4,0,0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
4979,2017-08-07,22,27,47,1,0,0,206.170000,171.635933,31070.817342,45.931081,5.0,2.0,1.479730,1.0,5.0,1.0
4980,2017-08-07,22,39,97,2,0,0,168.235000,128.000000,21119.526316,39.631579,1.0,2.0,1.421053,1.0,6.0,1.0
4981,2017-08-07,22,18,27,1,0,0,91.040573,70.852205,12465.087046,23.868510,5.0,5.0,1.607477,1.0,9.0,1.0
4982,2017-08-07,22,51,112,1,0,0,NaN,71.000000,10761.833333,20.000000,1.0,0.0,1.000000,1.0,1.0,1.0
4983,2017-08-07,22,146,8,1,0,0,NaN,88.500000,10705.333333,20.333333,0.0,0.0,1.500000,1.0,3.0,1.0
4984,2017-08-07,22,24,71,3,0,0,104.160361,83.262439,14373.561129,25.571616,1.0,5.0,1.858156,1.0,17.0,1.0
4985,2017-08-07,22,15,90,1,0,0,98.231639,78.945000,13062.195013,25.248546,1.0,5.0,1.863158,1.0,10.0,1.0
4986,2017-08-07,22,59,23,1,0,0,59.000000,NaN,13498.500000,25.500000,1.0,5.0,1.000000,1.0,1.0,1.0
4987,2017-08-07,22,47,64,1,0,0,122.734167,129.450417,26118.223770,33.992897,2.0,5.0,1.440860,1.0,11.0,1.0
4988,2017-08-07,22,10,74,1,0,0,95.411667,81.709630,14011.948496,26.351253,5.0,1.0,1.873684,1.0,8.0,1.0
4989,2017-08-07,22,50,45,1,0,0,54.000000,46.800444,6540.953795,12.051155,1.0,5.0,1.287129,1.0,6.0,1.0
4990,2017-08-07,22,47,62,1,0,0,163.782857,187.806364,35109.272989,50.929310,2.0,5.0,1.327586,1.0,6.0,1.0
4991,2017-08-07,22,39,58,1,0,0,NaN,150.500000,21903.765432,41.981481,1.0,2.0,1.518519,1.0,4.0,1.0
4992,2017-08-07,22,24,51,1,0,0,85.216645,69.174595,11887.392869,21.634554,1.0,1.0,2.113537,1.0,30.0,1.0
4993,2017-08-07,22,109,51,1,0,0,85.560000,113.230000,18766.500000,31.500000,1.0,1.0,1.000000,1.0,1.0,1.0
4994,2017-08-07,22,6,39,2,0,0,50.484988,36.475926,4335.987689,8.090178,5.0,1.0,3.449782,2.0,52.0,1.0
4995,2017-08-07,22,47,15,1,0,0,189.613333,150.662857,29000.214815,43.341077,2.0,1.0,1.272727,1.0,5.0,1.0
4996,2017-08-07,22,76,80,1,0,0,90.002500,88.083125,12831.155172,23.224138,5.0,5.0,1.293103,1.0,6.0,1.0
4997,2017-08-07,22,9,50,1,0,0,94.000000,91.948750,17384.134058,33.750000,5.0,1.0,1.173913,1.0,4.0,1.0
4998,2017-08-07,22,79,3,1,0,0,35.405000,31.130130,3573.483168,6.630854,5.0,5.0,1.724771,1.0,12.0,1.0
4999,2017-08-07,22,41,36,1,0,0,NaN,109.000000,22413.071429,41.535714,5.0,2.0,1.285714,1.0,4.0,1.0

In [15]:
coord_se_mean = train_tr.groupby(['start_cluster','end_cluster'],as_index=False)['demand_count'].agg({'sloccl_eloccl_mean':'mean'})
coord_se_median = train_tr.groupby(['start_cluster','end_cluster'],as_index=False)['demand_count'].agg({'sloccl_eloccl_median':'median'})
coord_se_max = train_tr.groupby(['start_cluster','end_cluster'],as_index=False)['demand_count'].agg({'sloccl_eloccl_max':'max'})
coord_se_min = train_tr.groupby(['start_cluster','end_cluster'],as_index=False)['demand_count'].agg({'sloccl_eloccl_min':'min'})
train_tr = pd.merge(train_tr,coord_se_mean,on=['start_cluster','end_cluster'],how='left')
train_tr = pd.merge(train_tr,coord_se_median,on=['start_cluster','end_cluster'],how='left')
train_tr = pd.merge(train_tr,coord_se_max,on=['start_cluster','end_cluster'],how='left')
train_tr = pd.merge(train_tr,coord_se_min,on=['start_cluster','end_cluster'],how='left')
valid_tr = pd.merge(valid_tr,coord_se_mean,on=['start_cluster','end_cluster'],how='left')
valid_tr = pd.merge(valid_tr,coord_se_median,on=['start_cluster','end_cluster'],how='left')
valid_tr = pd.merge(valid_tr,coord_se_max,on=['start_cluster','end_cluster'],how='left')
valid_tr = pd.merge(valid_tr,coord_se_min,on=['start_cluster','end_cluster'],how='left')
valid_tr

# coord_se_mean = train_tr.groupby(['start_cluster','end_cluster'],as_index=False)['demand_count'].agg({'sloccl_eloccl_mean':'mean'})
# coord_se_median = train_tr.groupby(['start_cluster','end_cluster'],as_index=False)['demand_count'].agg({'sloccl_eloccl_median':'median'})
# coord_se_max = train_tr.groupby(['start_cluster','end_cluster'],as_index=False)['demand_count'].agg({'sloccl_eloccl_max':'max'})
# coord_se_min = train_tr.groupby(['start_cluster','end_cluster'],as_index=False)['demand_count'].agg({'sloccl_eloccl_min':'min'})
# train_tr = pd.merge(train_tr,coord_se_mean,on=['start_cluster','end_cluster'],how='left')
# train_tr = pd.merge(train_tr,coord_se_median,on=['start_cluster','end_cluster'],how='left')
# train_tr = pd.merge(train_tr,coord_se_max,on=['start_cluster','end_cluster'],how='left')
# train_tr = pd.merge(train_tr,coord_se_min,on=['start_cluster','end_cluster'],how='left')
# test = pd.merge(test,coord_se_mean,on=['start_cluster','end_cluster'],how='left')
# test = pd.merge(test,coord_se_median,on=['start_cluster','end_cluster'],how='left')
# test = pd.merge(test,coord_se_max,on=['start_cluster','end_cluster'],how='left')
# test = pd.merge(test,coord_se_min,on=['start_cluster','end_cluster'],how='left')
# test

,create_date,create_hour,start_geo_id,end_geo_id,demand_count,holiday,dayOfWeek,money_hour_mean,money_day_mean,dis_hour_mean,...,start_cluster,end_cluster,sloc_eloc_mean,sloc_eloc_median,sloc_eloc_max,sloc_eloc_min,sloccl_eloccl_mean,sloccl_eloccl_median,sloccl_eloccl_max,sloccl_eloccl_min
0,2017-08-01,0,120,74,1,0,1,NaN,NaN,NaN,...,5.0,1.0,NaN,NaN,NaN,NaN,1.928592,1.0,144.0,1.0
1,2017-08-01,0,9,109,1,0,1,78.272500,73.178333,11969.869863,...,5.0,1.0,1.232877,1.0,3.0,1.0,1.928592,1.0,144.0,1.0
2,2017-08-01,0,6,9,1,0,1,48.440833,52.794470,6517.478098,...,5.0,5.0,3.256410,2.0,33.0,1.0,1.854976,1.0,73.0,1.0
3,2017-08-01,0,24,63,1,0,1,73.226375,72.096218,11121.082444,...,1.0,5.0,2.173585,1.0,17.0,1.0,2.068860,1.0,198.0,1.0
4,2017-08-01,0,50,56,2,0,1,61.873333,54.676749,7830.344607,...,1.0,5.0,1.638418,1.0,13.0,1.0,2.068860,1.0,198.0,1.0
5,2017-08-01,0,6,70,1,0,1,85.500000,78.928470,12052.027640,...,5.0,5.0,1.792079,1.0,18.0,1.0,1.854976,1.0,73.0,1.0
6,2017-08-01,0,39,27,1,0,1,58.318755,54.224607,6883.846827,...,1.0,5.0,2.672000,2.0,24.0,1.0,2.068860,1.0,198.0,1.0
7,2017-08-01,0,5,203,1,0,1,133.000000,113.000000,24493.875000,...,4.0,4.0,1.000000,1.0,1.0,1.0,1.321060,1.0,13.0,1.0
8,2017-08-01,2,55,34,1,0,1,39.535000,41.284687,4538.260249,...,1.0,1.0,2.835227,2.0,23.0,1.0,2.311007,1.0,178.0,1.0
9,2017-08-01,2,24,76,1,0,1,45.492000,56.442873,7465.948594,...,1.0,5.0,2.222930,1.0,17.0,1.0,2.068860,1.0,198.0,1.0
10,2017-08-01,2,40,2,3,0,1,NaN,48.000000,8371.428571,...,3.0,1.0,1.214286,1.0,3.0,1.0,1.483888,1.0,34.0,1.0
11,2017-08-01,2,19,15,1,0,1,NaN,38.156236,3958.064338,...,5.0,1.0,2.049724,2.0,16.0,1.0,1.928592,1.0,144.0,1.0
12,2017-08-01,2,24,94,1,0,1,69.163333,80.405812,11280.897349,...,1.0,1.0,2.255814,1.0,23.0,1.0,2.311007,1.0,178.0,1.0
13,2017-08-01,2,5,39,1,0,1,141.000000,118.014306,23972.281532,...,4.0,1.0,1.256757,1.0,4.0,1.0,1.401597,1.0,19.0,1.0
14,2017-08-01,2,24,3,1,0,1,51.347000,51.162467,7051.912512,...,1.0,5.0,2.868132,2.0,51.0,1.0,2.068860,1.0,198.0,1.0
15,2017-08-01,2,152,93,1,0,1,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,1.487186,1.0,20.0,1.0
16,2017-08-01,4,40,60,1,0,1,214.625000,226.500000,38126.730769,...,3.0,4.0,1.461538,1.0,4.0,1.0,1.403397,1.0,16.0,1.0
17,2017-08-01,4,3,60,2,0,1,163.570000,206.104167,29715.693333,...,5.0,4.0,1.500000,1.0,6.0,1.0,1.371720,1.0,37.0,1.0
18,2017-08-01,4,16,19,1,0,1,35.875000,38.002339,4366.878105,...,5.0,5.0,2.330189,1.0,20.0,1.0,1.854976,1.0,73.0,1.0
19,2017-08-01,4,140,47,1,0,1,NaN,NaN,53841.333333,...,1.0,2.0,1.000000,1.0,1.0,1.0,1.406877,1.0,23.0,1.0
20,2017-08-01,4,70,90,1,0,1,NaN,51.846270,6606.354600,...,5.0,5.0,1.586420,1.0,10.0,1.0,1.854976,1.0,73.0,1.0
21,2017-08-01,4,24,15,1,0,1,45.837500,50.432996,5808.238490,...,1.0,1.0,2.612195,2.0,18.0,1.0,2.311007,1.0,178.0,1.0
22,2017-08-01,4,41,16,1,0,1,NaN,47.591049,5671.137401,...,5.0,5.0,2.096085,1.0,29.0,1.0,1.854976,1.0,73.0,1.0
23,2017-08-01,4,6,19,1,0,1,33.223333,37.907110,3860.959904,...,5.0,5.0,2.802632,2.0,40.0,1.0,1.854976,1.0,73.0,1.0
24,2017-08-01,4,40,66,2,0,1,NaN,30.786667,6000.888889,...,3.0,0.0,1.000000,1.0,1.0,1.0,1.452022,1.0,16.0,1.0
25,2017-08-01,4,20,19,1,0,1,71.500000,80.748958,10894.901235,...,5.0,5.0,1.518519,1.0,6.0,1.0,1.854976,1.0,73.0,1.0
26,2017-08-01,4,88,61,1,0,1,NaN,38.409469,4113.891006,...,5.0,5.0,2.150442,1.0,15.0,1.0,1.854976,1.0,73.0,1.0
27,2017-08-01,6,204,49,1,0,1,31.470833,39.682143,3628.806818,...,0.0,5.0,1.227273,1.0,3.0,1.0,1.568431,1.0,36.0,1.0
28,2017-08-01,6,48,41,1,0,1,35.207750,40.654409,4086.465201,...,5.0,5.0,1.578723,1.0,18.0,1.0,1.854976,1.0,73.0,1.0
29,2017-08-01,6,48,210,1,0,1,78.000000,89.773333,16366.428571,...,5.0,4.0,1.285714,1.0,3.0,1.0,1.371720,1.0,37.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4970,2017-08-07,22,18,8,2,0,0,40.815177,32.717444,4122.597445,...,5.0,0.0,1.825545,1.0,12.0,1.0,1.501330,1.0,38.0,1.0
4971,2017-08-07,22,22,26,3,0,0,44.819637,34.871271,3875.855367,...,5.0,5.0,2.698297,2.0,40.0,1.0,1.854976,1.0,73.0,1.0
4972,2017-08-07,22,63,119,1,0,0,91.000000,111.077143,16005.428571,...,5.0,2.0,1.857143,1.0,7.0,1.0,1.404628,1.0,34.0,1.0
4973,2017-08-07,22,9,9,5,0,0,33.939605,28.677733,2513.793081,...,5.0,5.0,3.884146,3.0,70.0,1.0,1.854976,1.0,73.0,1.0
4974,2017-08-07,22,64,9,1,0,0,110.745000,73.190962,13175.305708,...,5.0,5.0,1.383562,1.0,6.0,1.0,1.854976,1.0,73.0,1.0
4975,2017-08-07,22,1,191,1,0,0,115.720000,70.500000,16374.994253,...,1.0,5.0,1.344828,1.0,3.0,1.0,2.068860,1.0,198.0,1.0
4976,2017-08-07,22,70,30,1,0,0,76.616667,62.298750,9048.963768,...,5.0,1.0,1.456522,1.0,6.0,1.0,1.928592,1.0,144.0,1.0
4977,2017-08-07,22,63,102,1,0,0,66.000000,50.980625,6957.944444,...,5.0,0.0,1.233333,1.0,3.0,1.0,1.501330,1.0,38.0,1.0
4978,2017-08-07,22,163,110,4,0,0,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,1.487186,1.0,20.0,1.0
4979,2017-08-07,22,27,47,1,0,0,206.170000,171.635933,31070.817342,...,5.0,2.0,1.479730,1.0,5.0,1.0,1.404628,1.0,34.0,1.0
4980,2017-08-07,22,39,97,2,0,0,168.235000,128.000000,21119.526316,...,1.0,2.0,1.421053,1.0,6.0,1.0,1.406877,1.0,23.0,1.0
4981,2017-08-07,22,18,27,1,0,0,91.040573,70.852205,12465.087046,...,5.0,5.0,1.607477,1.0,9.0,1.0,1.854976,1.0,73.0,1.0
4982,2017-08-07,22,51,112,1,0,0,NaN,71.000000,10761.833333,...,1.0,0.0,1.000000,1.0,1.0,1.0,1.524182,1.0,47.0,1.0
4983,2017-08-07,22,146,8,1,0,0,NaN,88.500000,10705.333333,...,0.0,0.0,1.500000,1.0,3.0,1.0,1.487186,1.0,20.0,1.0
4984,2017-08-07,22,24,71,3,0,0,104.160361,83.262439,14373.561129,...,1.0,5.0,1.858156,1.0,17.0,1.0,2.068860,1.0,198.0,1.0
4985,2017-08-07,22,15,90,1,0,0,98.231639,78.945000,13062.195013,...,1.0,5.0,1.863158,1.0,10.0,1.0,2.068860,1.0,198.0,1.0
4986,2017-08-07,22,59,23,1,0,0,59.000000,NaN,13498.500000,...,1.0,5.0,1.000000,1.0,1.0,1.0,2.068860,1.0,198.0,1.0
4987,2017-08-07,22,47,64,1,0,0,122.734167,129.450417,26118.223770,...,2.0,5.0,1.440860,1.0,11.0,1.0,1.484299,1.0,21.0,1.0
4988,2017-08-07,22,10,74,1,0,0,95.411667,81.709630,14011.948496,...,5.0,1.0,1.873684,1.0,8.0,1.0,1.928592,1.0,144.0,1.0
4989,2017-08-07,22,50,45,1,0,0,54.000000,46.800444,6540.953795,...,1.0,5.0,1.287129,1.0,6.0,1.0,2.068860,1.0,198.0,1.0
4990,2017-08-07,22,47,62,1,0,0,163.782857,187.806364,35109.272989,...,2.0,5.0,1.327586,1.0,6.0,1.0,1.484299,1.0,21.0,1.0
4991,2017-08-07,22,39,58,1,0,0,NaN,150.500000,21903.765432,...,1.0,2.0,1.518519,1.0,4.0,1.0,1.406877,1.0,23.0,1.0
4992,2017-08-07,22,24,51,1,0,0,85.216645,69.174595,11887.392869,...,1.0,1.0,2.113537,1.0,30.0,1.0,2.311007,1.0,178.0,1.0
4993,2017-08-07,22,109,51,1,0,0,85.560000,113.230000,18766.500000,...,1.0,1.0,1.000000,1.0,1.0,1.0,2.311007,1.0,178.0,1.0
4994,2017-08-07,22,6,39,2,0,0,50.484988,36.475926,4335.987689,...,5.0,1.0,3.449782,2.0,52.0,1.0,1.928592,1.0,144.0,1.0
4995,2017-08-07,22,47,15,1,0,0,189.613333,150.662857,29000.214815,...,2.0,1.0,1.272727,1.0,5.0,1.0,1.503732,1.0,37.0,1.0
4996,2017-08-07,22,76,80,1,0,0,90.002500,88.083125,12831.155172,...,5.0,5.0,1.293103,1.0,6.0,1.0,1.854976,1.0,73.0,1.0
4997,2017-08-07,22,9,50,1,0,0,94.000000,91.948750,17384.134058,...,5.0,1.0,1.173913,1.0,4.0,1.0,1.928592,1.0,144.0,1.0
4998,2017-08-07,22,79,3,1,0,0,35.405000,31.130130,3573.483168,...,5.0,5.0,1.724771,1.0,12.0,1.0,1.854976,1.0,73.0,1.0
4999,2017-08-07,22,41,36,1,0,0,NaN,109.000000,22413.071429,...,5.0,2.0,1.285714,1.0,4.0,1.0,1.404628,1.0,34.0,1.0

In [16]:
coord_se_sum = train_tr.groupby(['start_geo_id','end_geo_id'],as_index=False)['demand_count'].agg({'sloc_eloc_sum':'sum'})
coord_s_sum = coord_se_sum.groupby('start_geo_id',as_index=False)['sloc_eloc_sum'].agg({'sloc_sum':'sum'})
coord_e_sum = coord_se_sum.groupby('end_geo_id',as_index=False)['sloc_eloc_sum'].agg({'eloc_sum':'sum'})
coord_se_sum = pd.merge(coord_se_sum,coord_s_sum,on='start_geo_id',how='left')
coord_se_sum = pd.merge(coord_se_sum,coord_e_sum,on='end_geo_id',how='left')
coord_se_sum.loc[:,'se_start_ratio'] = coord_se_sum['sloc_eloc_sum'] / (1.0 * coord_se_sum['sloc_sum'])
coord_se_sum.loc[:,'se_end_ratio'] = coord_se_sum['sloc_eloc_sum'] / (1.0 * coord_se_sum['eloc_sum'])
del coord_se_sum['sloc_eloc_sum'],coord_se_sum['sloc_sum'],coord_se_sum['eloc_sum']
# coord_se_sum
train_tr = pd.merge(train_tr,coord_se_sum,on=['start_geo_id','end_geo_id'],how='left')
valid_tr = pd.merge(valid_tr,coord_se_sum,on=['start_geo_id','end_geo_id'],how='left')
valid_tr

# coord_se_sum = train_tr.groupby(['start_geo_id','end_geo_id'],as_index=False)['demand_count'].agg({'sloc_eloc_sum':'sum'})
# coord_s_sum = coord_se_sum.groupby('start_geo_id',as_index=False)['sloc_eloc_sum'].agg({'sloc_sum':'sum'})
# coord_e_sum = coord_se_sum.groupby('end_geo_id',as_index=False)['sloc_eloc_sum'].agg({'eloc_sum':'sum'})
# coord_se_sum = pd.merge(coord_se_sum,coord_s_sum,on='start_geo_id',how='left')
# coord_se_sum = pd.merge(coord_se_sum,coord_e_sum,on='end_geo_id',how='left')
# coord_se_sum.loc[:,'se_start_ratio'] = coord_se_sum['sloc_eloc_sum'] / (1.0 * coord_se_sum['sloc_sum'])
# coord_se_sum.loc[:,'se_end_ratio'] = coord_se_sum['sloc_eloc_sum'] / (1.0 * coord_se_sum['eloc_sum'])
# del coord_se_sum['sloc_eloc_sum'],coord_se_sum['sloc_sum'],coord_se_sum['eloc_sum']
# # coord_se_sum
# train_tr = pd.merge(train_tr,coord_se_sum,on=['start_geo_id','end_geo_id'],how='left')
# test = pd.merge(test,coord_se_sum,on=['start_geo_id','end_geo_id'],how='left')
# test

,create_date,create_hour,start_geo_id,end_geo_id,demand_count,holiday,dayOfWeek,money_hour_mean,money_day_mean,dis_hour_mean,...,sloc_eloc_mean,sloc_eloc_median,sloc_eloc_max,sloc_eloc_min,sloccl_eloccl_mean,sloccl_eloccl_median,sloccl_eloccl_max,sloccl_eloccl_min,se_start_ratio,se_end_ratio
0,2017-08-01,0,120,74,1,0,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.928592,1.0,144.0,1.0,NaN,NaN
1,2017-08-01,0,9,109,1,0,1,78.272500,73.178333,11969.869863,...,1.232877,1.0,3.0,1.0,1.928592,1.0,144.0,1.0,0.003748,0.034312
2,2017-08-01,0,6,9,1,0,1,48.440833,52.794470,6517.478098,...,3.256410,2.0,33.0,1.0,1.854976,1.0,73.0,1.0,0.036285,0.057128
3,2017-08-01,0,24,63,1,0,1,73.226375,72.096218,11121.082444,...,2.173585,1.0,17.0,1.0,2.068860,1.0,198.0,1.0,0.009989,0.047310
4,2017-08-01,0,50,56,2,0,1,61.873333,54.676749,7830.344607,...,1.638418,1.0,13.0,1.0,2.068860,1.0,198.0,1.0,0.032746,0.018087
5,2017-08-01,0,6,70,1,0,1,85.500000,78.928470,12052.027640,...,1.792079,1.0,18.0,1.0,1.854976,1.0,73.0,1.0,0.009402,0.028854
6,2017-08-01,0,39,27,1,0,1,58.318755,54.224607,6883.846827,...,2.672000,2.0,24.0,1.0,2.068860,1.0,198.0,1.0,0.038408,0.036985
7,2017-08-01,0,5,203,1,0,1,133.000000,113.000000,24493.875000,...,1.000000,1.0,1.0,1.0,1.321060,1.0,13.0,1.0,0.000863,0.013652
8,2017-08-01,2,55,34,1,0,1,39.535000,41.284687,4538.260249,...,2.835227,2.0,23.0,1.0,2.311007,1.0,178.0,1.0,0.036386,0.080348
9,2017-08-01,2,24,76,1,0,1,45.492000,56.442873,7465.948594,...,2.222930,1.0,17.0,1.0,2.068860,1.0,198.0,1.0,0.012104,0.063013
10,2017-08-01,2,40,2,3,0,1,NaN,48.000000,8371.428571,...,1.214286,1.0,3.0,1.0,1.483888,1.0,34.0,1.0,0.005308,0.007331
11,2017-08-01,2,19,15,1,0,1,NaN,38.156236,3958.064338,...,2.049724,2.0,16.0,1.0,1.928592,1.0,144.0,1.0,0.059848,0.043859
12,2017-08-01,2,24,94,1,0,1,69.163333,80.405812,11280.897349,...,2.255814,1.0,23.0,1.0,2.311007,1.0,178.0,1.0,0.005046,0.110688
13,2017-08-01,2,5,39,1,0,1,141.000000,118.014306,23972.281532,...,1.256757,1.0,4.0,1.0,1.401597,1.0,19.0,1.0,0.020058,0.008114
14,2017-08-01,2,24,3,1,0,1,51.347000,51.162467,7051.912512,...,2.868132,2.0,51.0,1.0,2.068860,1.0,198.0,1.0,0.018104,0.118100
15,2017-08-01,2,152,93,1,0,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.487186,1.0,20.0,1.0,NaN,NaN
16,2017-08-01,4,40,60,1,0,1,214.625000,226.500000,38126.730769,...,1.461538,1.0,4.0,1.0,1.403397,1.0,16.0,1.0,0.005932,0.002204
17,2017-08-01,4,3,60,2,0,1,163.570000,206.104167,29715.693333,...,1.500000,1.0,6.0,1.0,1.371720,1.0,37.0,1.0,0.010681,0.008700
18,2017-08-01,4,16,19,1,0,1,35.875000,38.002339,4366.878105,...,2.330189,1.0,20.0,1.0,1.854976,1.0,73.0,1.0,0.023924,0.057621
19,2017-08-01,4,140,47,1,0,1,NaN,NaN,53841.333333,...,1.000000,1.0,1.0,1.0,1.406877,1.0,23.0,1.0,0.002402,0.000384
20,2017-08-01,4,70,90,1,0,1,NaN,51.846270,6606.354600,...,1.586420,1.0,10.0,1.0,1.854976,1.0,73.0,1.0,0.021205,0.022812
21,2017-08-01,4,24,15,1,0,1,45.837500,50.432996,5808.238490,...,2.612195,2.0,18.0,1.0,2.311007,1.0,178.0,1.0,0.018572,0.063305
22,2017-08-01,4,41,16,1,0,1,NaN,47.591049,5671.137401,...,2.096085,1.0,29.0,1.0,1.854976,1.0,73.0,1.0,0.045044,0.024697
23,2017-08-01,4,6,19,1,0,1,33.223333,37.907110,3860.959904,...,2.802632,2.0,40.0,1.0,1.854976,1.0,73.0,1.0,0.033194,0.099378
24,2017-08-01,4,40,66,2,0,1,NaN,30.786667,6000.888889,...,1.000000,1.0,1.0,1.0,1.452022,1.0,16.0,1.0,0.005620,0.009574
25,2017-08-01,4,20,19,1,0,1,71.500000,80.748958,10894.901235,...,1.518519,1.0,6.0,1.0,1.854976,1.0,73.0,1.0,0.011257,0.009565
26,2017-08-01,4,88,61,1,0,1,NaN,38.409469,4113.891006,...,2.150442,1.0,15.0,1.0,1.854976,1.0,73.0,1.0,0.048756,0.037190
27,2017-08-01,6,204,49,1,0,1,31.470833,39.682143,3628.806818,...,1.227273,1.0,3.0,1.0,1.568431,1.0,36.0,1.0,0.114894,0.017067
28,2017-08-01,6,48,41,1,0,1,35.207750,40.654409,4086.465201,...,1.578723,1.0,18.0,1.0,1.854976,1.0,73.0,1.0,0.090931,0.019362
29,2017-08-01,6,48,210,1,0,1,78.000000,89.773333,16366.428571,...,1.285714,1.0,3.0,1.0,1.371720,1.0,37.0,1.0,0.002206,0.025000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4970,2017-08-07,22,18,8,2,0,0,40.815177,32.717444,4122.597445,...,1.825545,1.0,12.0,1.0,1.501330,1.0,38.0,1.0,0.033089,0.060594
4971,2017-08-07,22,22,26,3,0,0,44.819637,34.871271,3875.855367,...,2.698297,2.0,40.0,1.0,1.854976,1.0,73.0,1.0,0.038860,0.078658
4972,2017-08-07,22,63,119,1,0,0,91.000000,111.077143,16005.428571,...,1.857143,1.0,7.0,1.0,1.404628,1.0,34.0,1.0,0.001028,0.008259
4973,2017-08-07,22,9,9,5,0,0,33.939605,28.677733,2513.793081,...,3.884146,3.0,70.0,1.0,1.854976,1.0,73.0,1.0,0.079575,0.078147
4974,2017-08-07,22,64,9,1,0,0,110.745000,73.190962,13175.305708,...,1.383562,1.0,6.0,1.0,1.854976,1.0,73.0,1.0,0.009672,0.004130
4975,2017-08-07,22,1,191,1,0,0,115.720000,70.500000,16374.994253,...,1.344828,1.0,3.0,1.0,2.068860,1.0,198.0,1.0,0.001945,0.031100
4976,2017-08-07,22,70,30,1,0,0,76.616667,62.298750,9048.963768,...,1.456522,1.0,6.0,1.0,1.928592,1.0,144.0,1.0,0.005528,0.014803
4977,2017-08-07,22,63,102,1,0,0,66.000000,50.980625,6957.944444,...,1.233333,1.0,3.0,1.0,1.501330,1.0,38.0,1.0,0.005851,0.042799
4978,2017-08-07,22,163,110,4,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.487186,1.0,20.0,1.0,NaN,NaN
4979,2017-08-07,22,27,47,1,0,0,206.170000,171.635933,31070.817342,...,1.479730,1.0,5.0,1.0,1.404628,1.0,34.0,1.0,0.008650,0.028048
4980,2017-08-07,22,39,97,2,0,0,168.235000,128.000000,21119.526316,...,1.421053,1.0,6.0,1.0,1.406877,1.0,23.0,1.0,0.001035,0.015836
4981,2017-08-07,22,18,27,1,0,0,91.040573,70.852205,12465.087046,...,1.607477,1.0,9.0,1.0,1.854976,1.0,73.0,1.0,0.019424,0.012697
4982,2017-08-07,22,51,112,1,0,0,NaN,71.000000,10761.833333,...,1.000000,1.0,1.0,1.0,1.524182,1.0,47.0,1.0,0.000832,0.016393
4983,2017-08-07,22,146,8,1,0,0,NaN,88.500000,10705.333333,...,1.500000,1.0,3.0,1.0,1.487186,1.0,20.0,1.0,0.009709,0.000931
4984,2017-08-07,22,24,71,3,0,0,104.160361,83.262439,14373.561129,...,1.858156,1.0,17.0,1.0,2.068860,1.0,198.0,1.0,0.004543,0.027798
4985,2017-08-07,22,15,90,1,0,0,98.231639,78.945000,13062.195013,...,1.863158,1.0,10.0,1.0,2.068860,1.0,198.0,1.0,0.007833,0.015711
4986,2017-08-07,22,59,23,1,0,0,59.000000,NaN,13498.500000,...,1.000000,1.0,1.0,1.0,2.068860,1.0,198.0,1.0,0.005025,0.001604
4987,2017-08-07,22,47,64,1,0,0,122.734167,129.450417,26118.223770,...,1.440860,1.0,11.0,1.0,1.484299,1.0,21.0,1.0,0.012159,0.011271
4988,2017-08-07,22,10,74,1,0,0,95.411667,81.709630,14011.948496,...,1.873684,1.0,8.0,1.0,1.928592,1.0,144.0,1.0,0.009346,0.051401
4989,2017-08-07,22,50,45,1,0,0,54.000000,46.800444,6540.953795,...,1.287129,1.0,6.0,1.0,2.068860,1.0,198.0,1.0,0.014679,0.044735
4990,2017-08-07,22,47,62,1,0,0,163.782857,187.806364,35109.272989,...,1.327586,1.0,6.0,1.0,1.484299,1.0,21.0,1.0,0.006987,0.010705
4991,2017-08-07,22,39,58,1,0,0,NaN,150.500000,21903.765432,...,1.518519,1.0,4.0,1.0,1.406877,1.0,23.0,1.0,0.001572,0.021602
4992,2017-08-07,22,24,51,1,0,0,85.216645,69.174595,11887.392869,...,2.113537,1.0,30.0,1.0,2.311007,1.0,178.0,1.0,0.008393,0.060184
4993,2017-08-07,22,109,51,1,0,0,85.560000,113.230000,18766.500000,...,1.000000,1.0,1.0,1.0,2.311007,1.0,178.0,1.0,0.003328,0.000995
4994,2017-08-07,22,6,39,2,0,0,50.484988,36.475926,4335.987689,...,3.449782,2.0,52.0,1.0,1.928592,1.0,144.0,1.0,0.041038,0.068926
4995,2017-08-07,22,47,15,1,0,0,189.613333,150.662857,29000.214815,...,1.272727,1.0,5.0,1.0,1.503732,1.0,37.0,1.0,0.011433,0.007448
4996,2017-08-07,22,76,80,1,0,0,90.002500,88.083125,12831.155172,...,1.293103,1.0,6.0,1.0,1.854976,1.0,73.0,1.0,0.005808,0.012483
4997,2017-08-07,22,9,50,1,0,0,94.000000,91.948750,17384.134058,...,1.173913,1.0,4.0,1.0,1.928592,1.0,144.0,1.0,0.002249,0.005874
4998,2017-08-07,22,79,3,1,0,0,35.405000,31.130130,3573.483168,...,1.724771,1.0,12.0,1.0,1.854976,1.0,73.0,1.0,0.042592,0.042534
4999,2017-08-07,22,41,36,1,0,0,NaN,109.000000,22413.071429,...,1.285714,1.0,4.0,1.0,1.404628,1.0,34.0,1.0,0.001377,0.004712

In [17]:
coord_se_sum = train_tr.groupby(['start_cluster','end_cluster'],as_index=False)['demand_count'].agg({'sloc_eloc_sum':'sum'})
coord_s_sum = coord_se_sum.groupby('start_cluster',as_index=False)['sloc_eloc_sum'].agg({'sloc_sum':'sum'})
coord_e_sum = coord_se_sum.groupby('end_cluster',as_index=False)['sloc_eloc_sum'].agg({'eloc_sum':'sum'})
coord_se_sum = pd.merge(coord_se_sum,coord_s_sum,on='start_cluster',how='left')
coord_se_sum = pd.merge(coord_se_sum,coord_e_sum,on='end_cluster',how='left')
coord_se_sum.loc[:,'se_start_cls_ratio'] = coord_se_sum['sloc_eloc_sum'] / (1.0 * coord_se_sum['sloc_sum'])
coord_se_sum.loc[:,'se_end_cls_ratio'] = coord_se_sum['sloc_eloc_sum'] / (1.0 * coord_se_sum['eloc_sum'])
del coord_se_sum['sloc_eloc_sum'],coord_se_sum['sloc_sum'],coord_se_sum['eloc_sum']
# coord_se_sum
train_tr = pd.merge(train_tr,coord_se_sum,on=['start_cluster','end_cluster'],how='left')
valid_tr = pd.merge(valid_tr,coord_se_sum,on=['start_cluster','end_cluster'],how='left')
valid_tr

# coord_se_sum = train_tr.groupby(['start_cluster','end_cluster'],as_index=False)['demand_count'].agg({'sloc_eloc_sum':'sum'})
# coord_s_sum = coord_se_sum.groupby('start_cluster',as_index=False)['sloc_eloc_sum'].agg({'sloc_sum':'sum'})
# coord_e_sum = coord_se_sum.groupby('end_cluster',as_index=False)['sloc_eloc_sum'].agg({'eloc_sum':'sum'})
# coord_se_sum = pd.merge(coord_se_sum,coord_s_sum,on='start_cluster',how='left')
# coord_se_sum = pd.merge(coord_se_sum,coord_e_sum,on='end_cluster',how='left')
# coord_se_sum.loc[:,'se_start_cls_ratio'] = coord_se_sum['sloc_eloc_sum'] / (1.0 * coord_se_sum['sloc_sum'])
# coord_se_sum.loc[:,'se_end_cls_ratio'] = coord_se_sum['sloc_eloc_sum'] / (1.0 * coord_se_sum['eloc_sum'])
# del coord_se_sum['sloc_eloc_sum'],coord_se_sum['sloc_sum'],coord_se_sum['eloc_sum']
# # coord_se_sum
# train_tr = pd.merge(train_tr,coord_se_sum,on=['start_cluster','end_cluster'],how='left')
# test = pd.merge(test,coord_se_sum,on=['start_cluster','end_cluster'],how='left')
# test

,create_date,create_hour,start_geo_id,end_geo_id,demand_count,holiday,dayOfWeek,money_hour_mean,money_day_mean,dis_hour_mean,...,sloc_eloc_max,sloc_eloc_min,sloccl_eloccl_mean,sloccl_eloccl_median,sloccl_eloccl_max,sloccl_eloccl_min,se_start_ratio,se_end_ratio,se_start_cls_ratio,se_end_cls_ratio
0,2017-08-01,0,120,74,1,0,1,NaN,NaN,NaN,...,NaN,NaN,1.928592,1.0,144.0,1.0,NaN,NaN,0.263846,0.518449
1,2017-08-01,0,9,109,1,0,1,78.272500,73.178333,11969.869863,...,3.0,1.0,1.928592,1.0,144.0,1.0,0.003748,0.034312,0.263846,0.518449
2,2017-08-01,0,6,9,1,0,1,48.440833,52.794470,6517.478098,...,33.0,1.0,1.854976,1.0,73.0,1.0,0.036285,0.057128,0.579441,0.566873
3,2017-08-01,0,24,63,1,0,1,73.226375,72.096218,11121.082444,...,17.0,1.0,2.068860,1.0,198.0,1.0,0.009989,0.047310,0.539159,0.289222
4,2017-08-01,0,50,56,2,0,1,61.873333,54.676749,7830.344607,...,13.0,1.0,2.068860,1.0,198.0,1.0,0.032746,0.018087,0.539159,0.289222
5,2017-08-01,0,6,70,1,0,1,85.500000,78.928470,12052.027640,...,18.0,1.0,1.854976,1.0,73.0,1.0,0.009402,0.028854,0.579441,0.566873
6,2017-08-01,0,39,27,1,0,1,58.318755,54.224607,6883.846827,...,24.0,1.0,2.068860,1.0,198.0,1.0,0.038408,0.036985,0.539159,0.289222
7,2017-08-01,0,5,203,1,0,1,133.000000,113.000000,24493.875000,...,1.0,1.0,1.321060,1.0,13.0,1.0,0.000863,0.013652,0.152406,0.122648
8,2017-08-01,2,55,34,1,0,1,39.535000,41.284687,4538.260249,...,23.0,1.0,2.311007,1.0,178.0,1.0,0.036386,0.080348,0.317524,0.342112
9,2017-08-01,2,24,76,1,0,1,45.492000,56.442873,7465.948594,...,17.0,1.0,2.068860,1.0,198.0,1.0,0.012104,0.063013,0.539159,0.289222
10,2017-08-01,2,40,2,3,0,1,NaN,48.000000,8371.428571,...,3.0,1.0,1.483888,1.0,34.0,1.0,0.005308,0.007331,0.217268,0.022613
11,2017-08-01,2,19,15,1,0,1,NaN,38.156236,3958.064338,...,16.0,1.0,1.928592,1.0,144.0,1.0,0.059848,0.043859,0.263846,0.518449
12,2017-08-01,2,24,94,1,0,1,69.163333,80.405812,11280.897349,...,23.0,1.0,2.311007,1.0,178.0,1.0,0.005046,0.110688,0.317524,0.342112
13,2017-08-01,2,5,39,1,0,1,141.000000,118.014306,23972.281532,...,4.0,1.0,1.401597,1.0,19.0,1.0,0.020058,0.008114,0.238616,0.028735
14,2017-08-01,2,24,3,1,0,1,51.347000,51.162467,7051.912512,...,51.0,1.0,2.068860,1.0,198.0,1.0,0.018104,0.118100,0.539159,0.289222
15,2017-08-01,2,152,93,1,0,1,NaN,NaN,NaN,...,NaN,NaN,1.487186,1.0,20.0,1.0,NaN,NaN,0.110960,0.109537
16,2017-08-01,4,40,60,1,0,1,214.625000,226.500000,38126.730769,...,4.0,1.0,1.403397,1.0,16.0,1.0,0.005932,0.002204,0.051978,0.036152
17,2017-08-01,4,3,60,2,0,1,163.570000,206.104167,29715.693333,...,6.0,1.0,1.371720,1.0,37.0,1.0,0.010681,0.008700,0.033091,0.434533
18,2017-08-01,4,16,19,1,0,1,35.875000,38.002339,4366.878105,...,20.0,1.0,1.854976,1.0,73.0,1.0,0.023924,0.057621,0.579441,0.566873
19,2017-08-01,4,140,47,1,0,1,NaN,NaN,53841.333333,...,1.0,1.0,1.406877,1.0,23.0,1.0,0.002402,0.000384,0.037296,0.237244
20,2017-08-01,4,70,90,1,0,1,NaN,51.846270,6606.354600,...,10.0,1.0,1.854976,1.0,73.0,1.0,0.021205,0.022812,0.579441,0.566873
21,2017-08-01,4,24,15,1,0,1,45.837500,50.432996,5808.238490,...,18.0,1.0,2.311007,1.0,178.0,1.0,0.018572,0.063305,0.317524,0.342112
22,2017-08-01,4,41,16,1,0,1,NaN,47.591049,5671.137401,...,29.0,1.0,1.854976,1.0,73.0,1.0,0.045044,0.024697,0.579441,0.566873
23,2017-08-01,4,6,19,1,0,1,33.223333,37.907110,3860.959904,...,40.0,1.0,1.854976,1.0,73.0,1.0,0.033194,0.099378,0.579441,0.566873
24,2017-08-01,4,40,66,2,0,1,NaN,30.786667,6000.888889,...,1.0,1.0,1.452022,1.0,16.0,1.0,0.005620,0.009574,0.071990,0.035630
25,2017-08-01,4,20,19,1,0,1,71.500000,80.748958,10894.901235,...,6.0,1.0,1.854976,1.0,73.0,1.0,0.011257,0.009565,0.579441,0.566873
26,2017-08-01,4,88,61,1,0,1,NaN,38.409469,4113.891006,...,15.0,1.0,1.854976,1.0,73.0,1.0,0.048756,0.037190,0.579441,0.566873
27,2017-08-01,6,204,49,1,0,1,31.470833,39.682143,3628.806818,...,3.0,1.0,1.568431,1.0,36.0,1.0,0.114894,0.017067,0.506919,0.052393
28,2017-08-01,6,48,41,1,0,1,35.207750,40.654409,4086.465201,...,18.0,1.0,1.854976,1.0,73.0,1.0,0.090931,0.019362,0.579441,0.566873
29,2017-08-01,6,48,210,1,0,1,78.000000,89.773333,16366.428571,...,3.0,1.0,1.371720,1.0,37.0,1.0,0.002206,0.025000,0.033091,0.434533
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4970,2017-08-07,22,18,8,2,0,0,40.815177,32.717444,4122.597445,...,12.0,1.0,1.501330,1.0,38.0,1.0,0.033089,0.060594,0.054058,0.505128
4971,2017-08-07,22,22,26,3,0,0,44.819637,34.871271,3875.855367,...,40.0,1.0,1.854976,1.0,73.0,1.0,0.038860,0.078658,0.579441,0.566873
4972,2017-08-07,22,63,119,1,0,0,91.000000,111.077143,16005.428571,...,7.0,1.0,1.404628,1.0,34.0,1.0,0.001028,0.008259,0.040195,0.466298
4973,2017-08-07,22,9,9,5,0,0,33.939605,28.677733,2513.793081,...,70.0,1.0,1.854976,1.0,73.0,1.0,0.079575,0.078147,0.579441,0.566873
4974,2017-08-07,22,64,9,1,0,0,110.745000,73.190962,13175.305708,...,6.0,1.0,1.854976,1.0,73.0,1.0,0.009672,0.004130,0.579441,0.566873
4975,2017-08-07,22,1,191,1,0,0,115.720000,70.500000,16374.994253,...,3.0,1.0,2.068860,1.0,198.0,1.0,0.001945,0.031100,0.539159,0.289222
4976,2017-08-07,22,70,30,1,0,0,76.616667,62.298750,9048.963768,...,6.0,1.0,1.928592,1.0,144.0,1.0,0.005528,0.014803,0.263846,0.518449
4977,2017-08-07,22,63,102,1,0,0,66.000000,50.980625,6957.944444,...,3.0,1.0,1.501330,1.0,38.0,1.0,0.005851,0.042799,0.054058,0.505128
4978,2017-08-07,22,163,110,4,0,0,NaN,NaN,NaN,...,NaN,NaN,1.487186,1.0,20.0,1.0,NaN,NaN,0.110960,0.109537
4979,2017-08-07,22,27,47,1,0,0,206.170000,171.635933,31070.817342,...,5.0,1.0,1.404628,1.0,34.0,1.0,0.008650,0.028048,0.040195,0.466298
4980,2017-08-07,22,39,97,2,0,0,168.235000,128.000000,21119.526316,...,6.0,1.0,1.406877,1.0,23.0,1.0,0.001035,0.015836,0.037296,0.237244
4981,2017-08-07,22,18,27,1,0,0,91.040573,70.852205,12465.087046,...,9.0,1.0,1.854976,1.0,73.0,1.0,0.019424,0.012697,0.579441,0.566873
4982,2017-08-07,22,51,112,1,0,0,NaN,71.000000,10761.833333,...,1.0,1.0,1.524182,1.0,47.0,1.0,0.000832,0.016393,0.045842,0.234875
4983,2017-08-07,22,146,8,1,0,0,NaN,88.500000,10705.333333,...,3.0,1.0,1.487186,1.0,20.0,1.0,0.009709,0.000931,0.110960,0.109537
4984,2017-08-07,22,24,71,3,0,0,104.160361,83.262439,14373.561129,...,17.0,1.0,2.068860,1.0,198.0,1.0,0.004543,0.027798,0.539159,0.289222
4985,2017-08-07,22,15,90,1,0,0,98.231639,78.945000,13062.195013,...,10.0,1.0,2.068860,1.0,198.0,1.0,0.007833,0.015711,0.539159,0.289222
4986,2017-08-07,22,59,23,1,0,0,59.000000,NaN,13498.500000,...,1.0,1.0,2.068860,1.0,198.0,1.0,0.005025,0.001604,0.539159,0.289222
4987,2017-08-07,22,47,64,1,0,0,122.734167,129.450417,26118.223770,...,11.0,1.0,1.484299,1.0,21.0,1.0,0.012159,0.011271,0.455874,0.040350
4988,2017-08-07,22,10,74,1,0,0,95.411667,81.709630,14011.948496,...,8.0,1.0,1.928592,1.0,144.0,1.0,0.009346,0.051401,0.263846,0.518449
4989,2017-08-07,22,50,45,1,0,0,54.000000,46.800444,6540.953795,...,6.0,1.0,2.068860,1.0,198.0,1.0,0.014679,0.044735,0.539159,0.289222
4990,2017-08-07,22,47,62,1,0,0,163.782857,187.806364,35109.272989,...,6.0,1.0,1.484299,1.0,21.0,1.0,0.006987,0.010705,0.455874,0.040350
4991,2017-08-07,22,39,58,1,0,0,NaN,150.500000,21903.765432,...,4.0,1.0,1.406877,1.0,23.0,1.0,0.001572,0.021602,0.037296,0.237244
4992,2017-08-07,22,24,51,1,0,0,85.216645,69.174595,11887.392869,...,30.0,1.0,2.311007,1.0,178.0,1.0,0.008393,0.060184,0.317524,0.342112
4993,2017-08-07,22,109,51,1,0,0,85.560000,113.230000,18766.500000,...,1.0,1.0,2.311007,1.0,178.0,1.0,0.003328,0.000995,0.317524,0.342112
4994,2017-08-07,22,6,39,2,0,0,50.484988,36.475926,4335.987689,...,52.0,1.0,1.928592,1.0,144.0,1.0,0.041038,0.068926,0.263846,0.518449
4995,2017-08-07,22,47,15,1,0,0,189.613333,150.662857,29000.214815,...,5.0,1.0,1.503732,1.0,37.0,1.0,0.011433,0.007448,0.236511,0.042046
4996,2017-08-07,22,76,80,1,0,0,90.002500,88.083125,12831.155172,...,6.0,1.0,1.854976,1.0,73.0,1.0,0.005808,0.012483,0.579441,0.566873
4997,2017-08-07,22,9,50,1,0,0,94.000000,91.948750,17384.134058,...,4.0,1.0,1.928592,1.0,144.0,1.0,0.002249,0.005874,0.263846,0.518449
4998,2017-08-07,22,79,3,1,0,0,35.405000,31.130130,3573.483168,...,12.0,1.0,1.854976,1.0,73.0,1.0,0.042592,0.042534,0.579441,0.566873
4999,2017-08-07,22,41,36,1,0,0,NaN,109.000000,22413.071429,...,4.0,1.0,1.404628,1.0,34.0,1.0,0.001377,0.004712,0.040195,0.466298

### Time

In [18]:
map_hour = {1:1,2:1,3:1,4:1,5:1,6:1,7:2,8:2,9:2,10:3,11:3,12:3,13:4,14:4,15:4,16:5,17:5,18:5,19:6,20:6,21:6,22:0,23:0,0:0}
train_tr.loc[:,'hour_cls'] = train_tr['create_hour'].map(lambda x: map_hour[x])
valid_tr.loc[:,'hour_cls'] = valid_tr['create_hour'].map(lambda x: map_hour[x])
valid_tr

# map_hour = {1:1,2:1,3:1,4:1,5:1,6:1,7:2,8:2,9:2,10:3,11:3,12:3,13:4,14:4,15:4,16:5,17:5,18:5,19:6,20:6,21:6,22:0,23:0,0:0}
# train_tr.loc[:,'hour_cls'] = train_tr['create_hour'].map(lambda x: map_hour[x])
# test.loc[:,'hour_cls'] = test['create_hour'].map(lambda x: map_hour[x])
# test

,create_date,create_hour,start_geo_id,end_geo_id,demand_count,holiday,dayOfWeek,money_hour_mean,money_day_mean,dis_hour_mean,...,sloc_eloc_min,sloccl_eloccl_mean,sloccl_eloccl_median,sloccl_eloccl_max,sloccl_eloccl_min,se_start_ratio,se_end_ratio,se_start_cls_ratio,se_end_cls_ratio,hour_cls
0,2017-08-01,0,120,74,1,0,1,NaN,NaN,NaN,...,NaN,1.928592,1.0,144.0,1.0,NaN,NaN,0.263846,0.518449,0
1,2017-08-01,0,9,109,1,0,1,78.272500,73.178333,11969.869863,...,1.0,1.928592,1.0,144.0,1.0,0.003748,0.034312,0.263846,0.518449,0
2,2017-08-01,0,6,9,1,0,1,48.440833,52.794470,6517.478098,...,1.0,1.854976,1.0,73.0,1.0,0.036285,0.057128,0.579441,0.566873,0
3,2017-08-01,0,24,63,1,0,1,73.226375,72.096218,11121.082444,...,1.0,2.068860,1.0,198.0,1.0,0.009989,0.047310,0.539159,0.289222,0
4,2017-08-01,0,50,56,2,0,1,61.873333,54.676749,7830.344607,...,1.0,2.068860,1.0,198.0,1.0,0.032746,0.018087,0.539159,0.289222,0
5,2017-08-01,0,6,70,1,0,1,85.500000,78.928470,12052.027640,...,1.0,1.854976,1.0,73.0,1.0,0.009402,0.028854,0.579441,0.566873,0
6,2017-08-01,0,39,27,1,0,1,58.318755,54.224607,6883.846827,...,1.0,2.068860,1.0,198.0,1.0,0.038408,0.036985,0.539159,0.289222,0
7,2017-08-01,0,5,203,1,0,1,133.000000,113.000000,24493.875000,...,1.0,1.321060,1.0,13.0,1.0,0.000863,0.013652,0.152406,0.122648,0
8,2017-08-01,2,55,34,1,0,1,39.535000,41.284687,4538.260249,...,1.0,2.311007,1.0,178.0,1.0,0.036386,0.080348,0.317524,0.342112,1
9,2017-08-01,2,24,76,1,0,1,45.492000,56.442873,7465.948594,...,1.0,2.068860,1.0,198.0,1.0,0.012104,0.063013,0.539159,0.289222,1
10,2017-08-01,2,40,2,3,0,1,NaN,48.000000,8371.428571,...,1.0,1.483888,1.0,34.0,1.0,0.005308,0.007331,0.217268,0.022613,1
11,2017-08-01,2,19,15,1,0,1,NaN,38.156236,3958.064338,...,1.0,1.928592,1.0,144.0,1.0,0.059848,0.043859,0.263846,0.518449,1
12,2017-08-01,2,24,94,1,0,1,69.163333,80.405812,11280.897349,...,1.0,2.311007,1.0,178.0,1.0,0.005046,0.110688,0.317524,0.342112,1
13,2017-08-01,2,5,39,1,0,1,141.000000,118.014306,23972.281532,...,1.0,1.401597,1.0,19.0,1.0,0.020058,0.008114,0.238616,0.028735,1
14,2017-08-01,2,24,3,1,0,1,51.347000,51.162467,7051.912512,...,1.0,2.068860,1.0,198.0,1.0,0.018104,0.118100,0.539159,0.289222,1
15,2017-08-01,2,152,93,1,0,1,NaN,NaN,NaN,...,NaN,1.487186,1.0,20.0,1.0,NaN,NaN,0.110960,0.109537,1
16,2017-08-01,4,40,60,1,0,1,214.625000,226.500000,38126.730769,...,1.0,1.403397,1.0,16.0,1.0,0.005932,0.002204,0.051978,0.036152,1
17,2017-08-01,4,3,60,2,0,1,163.570000,206.104167,29715.693333,...,1.0,1.371720,1.0,37.0,1.0,0.010681,0.008700,0.033091,0.434533,1
18,2017-08-01,4,16,19,1,0,1,35.875000,38.002339,4366.878105,...,1.0,1.854976,1.0,73.0,1.0,0.023924,0.057621,0.579441,0.566873,1
19,2017-08-01,4,140,47,1,0,1,NaN,NaN,53841.333333,...,1.0,1.406877,1.0,23.0,1.0,0.002402,0.000384,0.037296,0.237244,1
20,2017-08-01,4,70,90,1,0,1,NaN,51.846270,6606.354600,...,1.0,1.854976,1.0,73.0,1.0,0.021205,0.022812,0.579441,0.566873,1
21,2017-08-01,4,24,15,1,0,1,45.837500,50.432996,5808.238490,...,1.0,2.311007,1.0,178.0,1.0,0.018572,0.063305,0.317524,0.342112,1
22,2017-08-01,4,41,16,1,0,1,NaN,47.591049,5671.137401,...,1.0,1.854976,1.0,73.0,1.0,0.045044,0.024697,0.579441,0.566873,1
23,2017-08-01,4,6,19,1,0,1,33.223333,37.907110,3860.959904,...,1.0,1.854976,1.0,73.0,1.0,0.033194,0.099378,0.579441,0.566873,1
24,2017-08-01,4,40,66,2,0,1,NaN,30.786667,6000.888889,...,1.0,1.452022,1.0,16.0,1.0,0.005620,0.009574,0.071990,0.035630,1
25,2017-08-01,4,20,19,1,0,1,71.500000,80.748958,10894.901235,...,1.0,1.854976,1.0,73.0,1.0,0.011257,0.009565,0.579441,0.566873,1
26,2017-08-01,4,88,61,1,0,1,NaN,38.409469,4113.891006,...,1.0,1.854976,1.0,73.0,1.0,0.048756,0.037190,0.579441,0.566873,1
27,2017-08-01,6,204,49,1,0,1,31.470833,39.682143,3628.806818,...,1.0,1.568431,1.0,36.0,1.0,0.114894,0.017067,0.506919,0.052393,1
28,2017-08-01,6,48,41,1,0,1,35.207750,40.654409,4086.465201,...,1.0,1.854976,1.0,73.0,1.0,0.090931,0.019362,0.579441,0.566873,1
29,2017-08-01,6,48,210,1,0,1,78.000000,89.773333,16366.428571,...,1.0,1.371720,1.0,37.0,1.0,0.002206,0.025000,0.033091,0.434533,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4970,2017-08-07,22,18,8,2,0,0,40.815177,32.717444,4122.597445,...,1.0,1.501330,1.0,38.0,1.0,0.033089,0.060594,0.054058,0.505128,0
4971,2017-08-07,22,22,26,3,0,0,44.819637,34.871271,3875.855367,...,1.0,1.854976,1.0,73.0,1.0,0.038860,0.078658,0.579441,0.566873,0
4972,2017-08-07,22,63,119,1,0,0,91.000000,111.077143,16005.428571,...,1.0,1.404628,1.0,34.0,1.0,0.001028,0.008259,0.040195,0.466298,0
4973,2017-08-07,22,9,9,5,0,0,33.939605,28.677733,2513.793081,...,1.0,1.854976,1.0,73.0,1.0,0.079575,0.078147,0.579441,0.566873,0
4974,2017-08-07,22,64,9,1,0,0,110.745000,73.190962,13175.305708,...,1.0,1.854976,1.0,73.0,1.0,0.009672,0.004130,0.579441,0.566873,0
4975,2017-08-07,22,1,191,1,0,0,115.720000,70.500000,16374.994253,...,1.0,2.068860,1.0,198.0,1.0,0.001945,0.031100,0.539159,0.289222,0
4976,2017-08-07,22,70,30,1,0,0,76.616667,62.298750,9048.963768,...,1.0,1.928592,1.0,144.0,1.0,0.005528,0.014803,0.263846,0.518449,0
4977,2017-08-07,22,63,102,1,0,0,66.000000,50.980625,6957.944444,...,1.0,1.501330,1.0,38.0,1.0,0.005851,0.042799,0.054058,0.505128,0
4978,2017-08-07,22,163,110,4,0,0,NaN,NaN,NaN,...,NaN,1.487186,1.0,20.0,1.0,NaN,NaN,0.110960,0.109537,0
4979,2017-08-07,22,27,47,1,0,0,206.170000,171.635933,31070.817342,...,1.0,1.404628,1.0,34.0,1.0,0.008650,0.028048,0.040195,0.466298,0
4980,2017-08-07,22,39,97,2,0,0,168.235000,128.000000,21119.526316,...,1.0,1.406877,1.0,23.0,1.0,0.001035,0.015836,0.037296,0.237244,0
4981,2017-08-07,22,18,27,1,0,0,91.040573,70.852205,12465.087046,...,1.0,1.854976,1.0,73.0,1.0,0.019424,0.012697,0.579441,0.566873,0
4982,2017-08-07,22,51,112,1,0,0,NaN,71.000000,10761.833333,...,1.0,1.524182,1.0,47.0,1.0,0.000832,0.016393,0.045842,0.234875,0
4983,2017-08-07,22,146,8,1,0,0,NaN,88.500000,10705.333333,...,1.0,1.487186,1.0,20.0,1.0,0.009709,0.000931,0.110960,0.109537,0
4984,2017-08-07,22,24,71,3,0,0,104.160361,83.262439,14373.561129,...,1.0,2.068860,1.0,198.0,1.0,0.004543,0.027798,0.539159,0.289222,0
4985,2017-08-07,22,15,90,1,0,0,98.231639,78.945000,13062.195013,...,1.0,2.068860,1.0,198.0,1.0,0.007833,0.015711,0.539159,0.289222,0
4986,2017-08-07,22,59,23,1,0,0,59.000000,NaN,13498.500000,...,1.0,2.068860,1.0,198.0,1.0,0.005025,0.001604,0.539159,0.289222,0
4987,2017-08-07,22,47,64,1,0,0,122.734167,129.450417,26118.223770,...,1.0,1.484299,1.0,21.0,1.0,0.012159,0.011271,0.455874,0.040350,0
4988,2017-08-07,22,10,74,1,0,0,95.411667,81.709630,14011.948496,...,1.0,1.928592,1.0,144.0,1.0,0.009346,0.051401,0.263846,0.518449,0
4989,2017-08-07,22,50,45,1,0,0,54.000000,46.800444,6540.953795,...,1.0,2.068860,1.0,198.0,1.0,0.014679,0.044735,0.539159,0.289222,0
4990,2017-08-07,22,47,62,1,0,0,163.782857,187.806364,35109.272989,...,1.0,1.484299,1.0,21.0,1.0,0.006987,0.010705,0.455874,0.040350,0
4991,2017-08-07,22,39,58,1,0,0,NaN,150.500000,21903.765432,...,1.0,1.406877,1.0,23.0,1.0,0.001572,0.021602,0.037296,0.237244,0
4992,2017-08-07,22,24,51,1,0,0,85.216645,69.174595,11887.392869,...,1.0,2.311007,1.0,178.0,1.0,0.008393,0.060184,0.317524,0.342112,0
4993,2017-08-07,22,109,51,1,0,0,85.560000,113.230000,18766.500000,...,1.0,2.311007,1.0,178.0,1.0,0.003328,0.000995,0.317524,0.342112,0
4994,2017-08-07,22,6,39,2,0,0,50.484988,36.475926,4335.987689,...,1.0,1.928592,1.0,144.0,1.0,0.041038,0.068926,0.263846,0.518449,0
4995,2017-08-07,22,47,15,1,0,0,189.613333,150.662857,29000.214815,...,1.0,1.503732,1.0,37.0,1.0,0.011433,0.007448,0.236511,0.042046,0
4996,2017-08-07,22,76,80,1,0,0,90.002500,88.083125,12831.155172,...,1.0,1.854976,1.0,73.0,1.0,0.005808,0.012483,0.579441,0.566873,0
4997,2017-08-07,22,9,50,1,0,0,94.000000,91.948750,17384.134058,...,1.0,1.928592,1.0,144.0,1.0,0.002249,0.005874,0.263846,0.518449,0
4998,2017-08-07,22,79,3,1,0,0,35.405000,31.130130,3573.483168,...,1.0,1.854976,1.0,73.0,1.0,0.042592,0.042534,0.579441,0.566873,0
4999,2017-08-07,22,41,36,1,0,0,NaN,109.000000,22413.071429,...,1.0,1.404628,1.0,34.0,1.0,0.001377,0.004712,0.040195,0.466298,0

In [19]:
coord_hour = train_tr.groupby('create_hour', as_index=False)['demand_count'].agg({'demand_count_h_avg':'std'})
coord_hour

    create_hour  demand_count_h_avg
0             0            1.935778
1             1            1.572084
2             2            0.739049
3             3            0.925068
4             4            0.971026
5             5            1.045984
6             6            1.257506
7             7            2.156388
8             8            3.425920
9             9            2.654506
10           10            1.125090
11           11            1.288213
12           12            1.252845
13           13            2.019655
14           14            1.448851
15           15            1.147384
16           16            1.435745
17           17            2.296841
18           18            2.081181
19           19            1.176402
20           20            1.533215
21           21            3.427579
22           22            3.145708
23           23            2.722501

### 3. Location + Time

In [20]:
coord_hour = train_tr.groupby(['create_hour','start_geo_id','end_geo_id'],as_index=False)['demand_count'].agg({'demand_count_h_avg':'mean'})
train_tr = pd.merge(train_tr,coord_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
valid_tr = pd.merge(valid_tr,coord_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
coord_hour = train_tr.groupby(['create_hour','start_geo_id','end_geo_id'],as_index=False)['demand_count'].agg({'demand_count_h_median':'median'})
train_tr = pd.merge(train_tr,coord_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
valid_tr = pd.merge(valid_tr,coord_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
coord_hour = train_tr.groupby(['create_hour','start_geo_id','end_geo_id'],as_index=False)['demand_count'].agg({'demand_count_h_max':'max'})
train_tr = pd.merge(train_tr,coord_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
valid_tr = pd.merge(valid_tr,coord_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
coord_hour = train_tr.groupby(['create_hour','start_geo_id','end_geo_id'],as_index=False)['demand_count'].agg({'demand_count_h_std':'std'})
train_tr = pd.merge(train_tr,coord_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
valid_tr = pd.merge(valid_tr,coord_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
valid_tr

# coord_hour = train_tr.groupby(['create_hour','start_geo_id','end_geo_id'],as_index=False)['demand_count'].agg({'demand_count_h_avg':'mean'})
# train_tr = pd.merge(train_tr,coord_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
# test = pd.merge(test,coord_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
# coord_hour = train_tr.groupby(['create_hour','start_geo_id','end_geo_id'],as_index=False)['demand_count'].agg({'demand_count_h_median':'median'})
# train_tr = pd.merge(train_tr,coord_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
# test = pd.merge(test,coord_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
# coord_hour = train_tr.groupby(['create_hour','start_geo_id','end_geo_id'],as_index=False)['demand_count'].agg({'demand_count_h_max':'max'})
# train_tr = pd.merge(train_tr,coord_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
# test = pd.merge(test,coord_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
# coord_hour = train_tr.groupby(['create_hour','start_geo_id','end_geo_id'],as_index=False)['demand_count'].agg({'demand_count_h_std':'std'})
# train_tr = pd.merge(train_tr,coord_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
# test = pd.merge(test,coord_hour,on=['create_hour','start_geo_id','end_geo_id'],how='left')
# test

,create_date,create_hour,start_geo_id,end_geo_id,demand_count,holiday,dayOfWeek,money_hour_mean,money_day_mean,dis_hour_mean,...,sloccl_eloccl_min,se_start_ratio,se_end_ratio,se_start_cls_ratio,se_end_cls_ratio,hour_cls,demand_count_h_avg,demand_count_h_median,demand_count_h_max,demand_count_h_std
0,2017-08-01,0,120,74,1,0,1,NaN,NaN,NaN,...,1.0,NaN,NaN,0.263846,0.518449,0,NaN,NaN,NaN,NaN
1,2017-08-01,0,9,109,1,0,1,78.272500,73.178333,11969.869863,...,1.0,0.003748,0.034312,0.263846,0.518449,0,1.250000,1.0,2.0,0.500000
2,2017-08-01,0,6,9,1,0,1,48.440833,52.794470,6517.478098,...,1.0,0.036285,0.057128,0.579441,0.566873,0,1.888889,1.0,4.0,1.364225
3,2017-08-01,0,24,63,1,0,1,73.226375,72.096218,11121.082444,...,1.0,0.009989,0.047310,0.539159,0.289222,0,2.714286,2.0,8.0,2.163636
4,2017-08-01,0,50,56,2,0,1,61.873333,54.676749,7830.344607,...,1.0,0.032746,0.018087,0.539159,0.289222,0,1.666667,1.0,3.0,1.154701
5,2017-08-01,0,6,70,1,0,1,85.500000,78.928470,12052.027640,...,1.0,0.009402,0.028854,0.579441,0.566873,0,1.000000,1.0,1.0,0.000000
6,2017-08-01,0,39,27,1,0,1,58.318755,54.224607,6883.846827,...,1.0,0.038408,0.036985,0.539159,0.289222,0,4.235294,2.0,24.0,5.836624
7,2017-08-01,0,5,203,1,0,1,133.000000,113.000000,24493.875000,...,1.0,0.000863,0.013652,0.152406,0.122648,0,1.000000,1.0,1.0,NaN
8,2017-08-01,2,55,34,1,0,1,39.535000,41.284687,4538.260249,...,1.0,0.036386,0.080348,0.317524,0.342112,1,1.000000,1.0,1.0,0.000000
9,2017-08-01,2,24,76,1,0,1,45.492000,56.442873,7465.948594,...,1.0,0.012104,0.063013,0.539159,0.289222,1,1.000000,1.0,1.0,0.000000
10,2017-08-01,2,40,2,3,0,1,NaN,48.000000,8371.428571,...,1.0,0.005308,0.007331,0.217268,0.022613,1,NaN,NaN,NaN,NaN
11,2017-08-01,2,19,15,1,0,1,NaN,38.156236,3958.064338,...,1.0,0.059848,0.043859,0.263846,0.518449,1,NaN,NaN,NaN,NaN
12,2017-08-01,2,24,94,1,0,1,69.163333,80.405812,11280.897349,...,1.0,0.005046,0.110688,0.317524,0.342112,1,1.000000,1.0,1.0,0.000000
13,2017-08-01,2,5,39,1,0,1,141.000000,118.014306,23972.281532,...,1.0,0.020058,0.008114,0.238616,0.028735,1,1.000000,1.0,1.0,0.000000
14,2017-08-01,2,24,3,1,0,1,51.347000,51.162467,7051.912512,...,1.0,0.018104,0.118100,0.539159,0.289222,1,1.400000,1.0,3.0,0.843274
15,2017-08-01,2,152,93,1,0,1,NaN,NaN,NaN,...,1.0,NaN,NaN,0.110960,0.109537,1,NaN,NaN,NaN,NaN
16,2017-08-01,4,40,60,1,0,1,214.625000,226.500000,38126.730769,...,1.0,0.005932,0.002204,0.051978,0.036152,1,4.000000,4.0,4.0,NaN
17,2017-08-01,4,3,60,2,0,1,163.570000,206.104167,29715.693333,...,1.0,0.010681,0.008700,0.033091,0.434533,1,1.000000,1.0,1.0,NaN
18,2017-08-01,4,16,19,1,0,1,35.875000,38.002339,4366.878105,...,1.0,0.023924,0.057621,0.579441,0.566873,1,1.250000,1.0,2.0,0.500000
19,2017-08-01,4,140,47,1,0,1,NaN,NaN,53841.333333,...,1.0,0.002402,0.000384,0.037296,0.237244,1,NaN,NaN,NaN,NaN
20,2017-08-01,4,70,90,1,0,1,NaN,51.846270,6606.354600,...,1.0,0.021205,0.022812,0.579441,0.566873,1,NaN,NaN,NaN,NaN
21,2017-08-01,4,24,15,1,0,1,45.837500,50.432996,5808.238490,...,1.0,0.018572,0.063305,0.317524,0.342112,1,1.500000,1.0,3.0,1.000000
22,2017-08-01,4,41,16,1,0,1,NaN,47.591049,5671.137401,...,1.0,0.045044,0.024697,0.579441,0.566873,1,NaN,NaN,NaN,NaN
23,2017-08-01,4,6,19,1,0,1,33.223333,37.907110,3860.959904,...,1.0,0.033194,0.099378,0.579441,0.566873,1,1.444444,1.0,2.0,0.527046
24,2017-08-01,4,40,66,2,0,1,NaN,30.786667,6000.888889,...,1.0,0.005620,0.009574,0.071990,0.035630,1,NaN,NaN,NaN,NaN
25,2017-08-01,4,20,19,1,0,1,71.500000,80.748958,10894.901235,...,1.0,0.011257,0.009565,0.579441,0.566873,1,1.000000,1.0,1.0,0.000000
26,2017-08-01,4,88,61,1,0,1,NaN,38.409469,4113.891006,...,1.0,0.048756,0.037190,0.579441,0.566873,1,NaN,NaN,NaN,NaN
27,2017-08-01,6,204,49,1,0,1,31.470833,39.682143,3628.806818,...,1.0,0.114894,0.017067,0.506919,0.052393,1,1.333333,1.0,2.0,0.516398
28,2017-08-01,6,48,41,1,0,1,35.207750,40.654409,4086.465201,...,1.0,0.090931,0.019362,0.579441,0.566873,1,1.583333,1.0,5.0,1.164500
29,2017-08-01,6,48,210,1,0,1,78.000000,89.773333,16366.428571,...,1.0,0.002206,0.025000,0.033091,0.434533,1,1.000000,1.0,1.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4970,2017-08-07,22,18,8,2,0,0,40.815177,32.717444,4122.597445,...,1.0,0.033089,0.060594,0.054058,0.505128,0,2.363636,2.0,9.0,2.300009
4971,2017-08-07,22,22,26,3,0,0,44.819637,34.871271,3875.855367,...,1.0,0.038860,0.078658,0.579441,0.566873,0,5.307692,2.5,40.0,7.953712
4972,2017-08-07,22,63,119,1,0,0,91.000000,111.077143,16005.428571,...,1.0,0.001028,0.008259,0.040195,0.466298,0,1.000000,1.0,1.0,NaN
4973,2017-08-07,22,9,9,5,0,0,33.939605,28.677733,2513.793081,...,1.0,0.079575,0.078147,0.579441,0.566873,0,3.192308,2.0,13.0,3.394339
4974,2017-08-07,22,64,9,1,0,0,110.745000,73.190962,13175.305708,...,1.0,0.009672,0.004130,0.579441,0.566873,0,2.000000,2.0,3.0,1.414214
4975,2017-08-07,22,1,191,1,0,0,115.720000,70.500000,16374.994253,...,1.0,0.001945,0.031100,0.539159,0.289222,0,1.000000,1.0,1.0,0.000000
4976,2017-08-07,22,70,30,1,0,0,76.616667,62.298750,9048.963768,...,1.0,0.005528,0.014803,0.263846,0.518449,0,1.666667,1.0,3.0,1.154701
4977,2017-08-07,22,63,102,1,0,0,66.000000,50.980625,6957.944444,...,1.0,0.005851,0.042799,0.054058,0.505128,0,1.000000,1.0,1.0,0.000000
4978,2017-08-07,22,163,110,4,0,0,NaN,NaN,NaN,...,1.0,NaN,NaN,0.110960,0.109537,0,NaN,NaN,NaN,NaN
4979,2017-08-07,22,27,47,1,0,0,206.170000,171.635933,31070.817342,...,1.0,0.008650,0.028048,0.040195,0.466298,0,1.500000,1.0,3.0,1.000000
4980,2017-08-07,22,39,97,2,0,0,168.235000,128.000000,21119.526316,...,1.0,0.001035,0.015836,0.037296,0.237244,0,4.000000,4.0,6.0,2.828427
4981,2017-08-07,22,18,27,1,0,0,91.040573,70.852205,12465.087046,...,1.0,0.019424,0.012697,0.579441,0.566873,0,2.375000,2.0,9.0,1.962142
4982,2017-08-07,22,51,112,1,0,0,NaN,71.000000,10761.833333,...,1.0,0.000832,0.016393,0.045842,0.234875,0,NaN,NaN,NaN,NaN
4983,2017-08-07,22,146,8,1,0,0,NaN,88.500000,10705.333333,...,1.0,0.009709,0.000931,0.110960,0.109537,0,NaN,NaN,NaN,NaN
4984,2017-08-07,22,24,71,3,0,0,104.160361,83.262439,14373.561129,...,1.0,0.004543,0.027798,0.539159,0.289222,0,3.777778,2.5,17.0,3.858612
4985,2017-08-07,22,15,90,1,0,0,98.231639,78.945000,13062.195013,...,1.0,0.007833,0.015711,0.539159,0.289222,0,3.083333,2.0,10.0,2.778434
4986,2017-08-07,22,59,23,1,0,0,59.000000,NaN,13498.500000,...,1.0,0.005025,0.001604,0.539159,0.289222,0,1.000000,1.0,1.0,NaN
4987,2017-08-07,22,47,64,1,0,0,122.734167,129.450417,26118.223770,...,1.0,0.012159,0.011271,0.455874,0.040350,0,2.166667,1.0,5.0,1.834848
4988,2017-08-07,22,10,74,1,0,0,95.411667,81.709630,14011.948496,...,1.0,0.009346,0.051401,0.263846,0.518449,0,2.636364,2.0,8.0,2.110579
4989,2017-08-07,22,50,45,1,0,0,54.000000,46.800444,6540.953795,...,1.0,0.014679,0.044735,0.539159,0.289222,0,1.000000,1.0,1.0,0.000000
4990,2017-08-07,22,47,62,1,0,0,163.782857,187.806364,35109.272989,...,1.0,0.006987,0.010705,0.455874,0.040350,0,2.142857,2.0,4.0,1.345185
4991,2017-08-07,22,39,58,1,0,0,NaN,150.500000,21903.765432,...,1.0,0.001572,0.021602,0.037296,0.237244,0,NaN,NaN,NaN,NaN
4992,2017-08-07,22,24,51,1,0,0,85.216645,69.174595,11887.392869,...,1.0,0.008393,0.060184,0.317524,0.342112,0,2.368421,2.0,8.0,1.977949
4993,2017-08-07,22,109,51,1,0,0,85.560000,113.230000,18766.500000,...,1.0,0.003328,0.000995,0.317524,0.342112,0,1.000000,1.0,1.0,0.000000
4994,2017-08-07,22,6,39,2,0,0,50.484988,36.475926,4335.987689,...,1.0,0.041038,0.068926,0.263846,0.518449,0,5.461538,3.5,20.0,5.186373
4995,2017-08-07,22,47,15,1,0,0,189.613333,150.662857,29000.214815,...,1.0,0.011433,0.007448,0.236511,0.042046,0,2.000000,2.0,3.0,1.000000
4996,2017-08-07,22,76,80,1,0,0,90.002500,88.083125,12831.155172,...,1.0,0.005808,0.012483,0.579441,0.566873,0,1.250000,1.0,2.0,0.500000
4997,2017-08-07,22,9,50,1,0,0,94.000000,91.948750,17384.134058,...,1.0,0.002249,0.005874,0.263846,0.518449,0,1.000000,1.0,1.0,0.000000
4998,2017-08-07,22,79,3,1,0,0,35.405000,31.130130,3573.483168,...,1.0,0.042592,0.042534,0.579441,0.566873,0,1.750000,2.0,2.0,0.500000
4999,2017-08-07,22,41,36,1,0,0,NaN,109.000000,22413.071429,...,1.0,0.001377,0.004712,0.040195,0.466298,0,NaN,NaN,NaN,NaN

In [29]:
coord_hour = train_tr.groupby(['create_hour','start_geo_id','end_geo_id'],as_index=False)['demand_count'].agg({'demand_count_h_avg':'mean'})
coord_hour_s = train_tr.groupby(['create_hour','start_geo_id'],as_index=False)['demand_count'].agg({'demand_count_same_h_avg':'mean'})
coord_hour_e = train_tr.groupby(['create_hour','end_geo_id'],as_index=False)['demand_count'].agg({'demand_count_same_h_avg':'mean'})
coord_hour_s

      create_hour  start_geo_id  demand_count_same_h_avg
0               0             0                 1.166667
1               0             1                 1.304054
2               0             2                 1.451613
3               0             3                 1.114286
4               0             4                 1.000000
5               0             5                 1.403175
6               0             6                 1.858942
7               0             7                 1.000000
8               0             8                 1.192771
9               0             9                 1.380952
10              0            10                 1.143791
11              0            11                 1.200000
12              0            12                 1.000000
13              0            13                 1.298507
14              0            14                 1.814480
15              0            15                 1.661417
16              0            16                 1.381148
17              0            17                 1.352041
18              0            18                 1.424000
19              0            19                 1.331081
20              0            20                 1.101449
21              0            21                 1.122995
22              0            22                 2.009158
23              0            23                 1.166667
24              0            24                 2.694897
25              0            25                 1.145833
26              0            26                 1.298246
27              0            27                 1.522876
28              0            29                 1.234375
29              0            30                 1.080000
...           ...           ...                      ...
8382           23           391                 1.000000
8383           23           412                 1.000000
8384           23           419                 1.000000
8385           23           425                 1.000000
8386           23           434                 1.000000
8387           23           437                 2.000000
8388           23           443                 1.000000
8389           23           470                 1.000000
8390           23           471                 3.000000
8391           23           472                 1.000000
8392           23           477                 1.000000
8393           23           478                 1.000000
8394           23           485                 1.000000
8395           23           488                 8.000000
8396           23           496                 1.000000
8397           23           506                 1.000000
8398           23           536                 1.000000
8399           23           579                 1.000000
8400           23           590                 1.000000
8401           23           596                 4.000000
8402           23           606                 1.000000
8403           23           626                 1.000000
8404           23           709                 3.000000
8405           23           739                 6.000000
8406           23           816                 1.000000
8407           23           950                 1.000000
8408           23           988                 1.000000
8409           23           998                 1.000000
8410           23          1197                 1.000000
8411           23          1222                 1.000000

[8412 rows x 3 columns]

In [21]:
coord = train_tr.groupby(['create_hour','start_geo_id'],as_index=False)['demand_count'].agg({'demand_count_start_avg':'mean'})
coord

      create_hour  start_geo_id  demand_count_start_avg
0               0             0                1.166667
1               0             1                1.304054
2               0             2                1.451613
3               0             3                1.114286
4               0             4                1.000000
5               0             5                1.403175
6               0             6                1.858942
7               0             7                1.000000
8               0             8                1.192771
9               0             9                1.380952
10              0            10                1.143791
11              0            11                1.200000
12              0            12                1.000000
13              0            13                1.298507
14              0            14                1.814480
15              0            15                1.661417
16              0            16                1.381148
17              0            17                1.352041
18              0            18                1.424000
19              0            19                1.331081
20              0            20                1.101449
21              0            21                1.122995
22              0            22                2.009158
23              0            23                1.166667
24              0            24                2.694897
25              0            25                1.145833
26              0            26                1.298246
27              0            27                1.522876
28              0            29                1.234375
29              0            30                1.080000
...           ...           ...                     ...
8382           23           391                1.000000
8383           23           412                1.000000
8384           23           419                1.000000
8385           23           425                1.000000
8386           23           434                1.000000
8387           23           437                2.000000
8388           23           443                1.000000
8389           23           470                1.000000
8390           23           471                3.000000
8391           23           472                1.000000
8392           23           477                1.000000
8393           23           478                1.000000
8394           23           485                1.000000
8395           23           488                8.000000
8396           23           496                1.000000
8397           23           506                1.000000
8398           23           536                1.000000
8399           23           579                1.000000
8400           23           590                1.000000
8401           23           596                4.000000
8402           23           606                1.000000
8403           23           626                1.000000
8404           23           709                3.000000
8405           23           739                6.000000
8406           23           816                1.000000
8407           23           950                1.000000
8408           23           988                1.000000
8409           23           998                1.000000
8410           23          1197                1.000000
8411           23          1222                1.000000

[8412 rows x 3 columns]

In [22]:
np.setdiff1d(train_tr.columns,valid_tr.columns)
# np.setdiff1d(test.columns,train_tr.columns)

array(['estimate_distance_mean', 'estimate_money_mean',
       'estimate_term_mean'], dtype=object)

### Training

In [23]:
do_not_use_list = ['create_date','demand_count','estimate_distance_mean','estimate_money_mean','estimate_term_mean','test_id']
predictors = [f for f in train_tr.columns if f not in do_not_use_list]
print predictors

['create_hour', 'start_geo_id', 'end_geo_id', 'holiday', 'dayOfWeek', 'money_hour_mean', 'money_day_mean', 'dis_hour_mean', 'term_hour_mean', 'start_cluster', 'end_cluster', 'sloc_eloc_mean', 'sloc_eloc_median', 'sloc_eloc_max', 'sloc_eloc_min', 'sloccl_eloccl_mean', 'sloccl_eloccl_median', 'sloccl_eloccl_max', 'sloccl_eloccl_min', 'se_start_ratio', 'se_end_ratio', 'se_start_cls_ratio', 'se_end_cls_ratio', 'hour_cls', 'demand_count_h_avg', 'demand_count_h_median', 'demand_count_h_max', 'demand_count_h_std']

In [24]:
import xgboost as xgb
params = {'min_child_weight': 100, 'eta': 0.1, 'colsample_bytree': 0.3, 'max_depth': 7,
                'subsample': 0.8, 'lambda': 1, 'nthread': 4, 'booster' : 'gbtree', 'silent': 1,
                'eval_metric': 'rmse', 'objective': 'reg:linear'}
boostRound = 150

train_tr_trip = train_tr[train_tr['create_date'] >= '2017-07-01'].copy()
# print train_feat_1[predictors]

xgbtrain = xgb.DMatrix(train_tr_trip[predictors], train_tr_trip['demand_count'],missing=np.nan)
# xgbvalid = xgb.DMatrix(test_feat_1[predictors])
model = xgb.train(params, xgbtrain, num_boost_round=boostRound)
param_score = pd.Series(model.get_fscore()).sort_values(ascending=False)

In [25]:
param_score

demand_count_h_avg       785
money_day_mean           728
sloc_eloc_mean           643
create_hour              544
money_hour_mean          526
demand_count_h_std       496
dis_hour_mean            432
dayOfWeek                427
demand_count_h_max       426
sloc_eloc_max            401
demand_count_h_median    371
se_start_ratio           354
se_end_ratio             311
start_geo_id             262
end_geo_id               251
hour_cls                 236
term_hour_mean           172
sloccl_eloccl_mean       139
sloccl_eloccl_max        105
holiday                  102
se_start_cls_ratio        80
sloc_eloc_median          70
se_end_cls_ratio          70
start_cluster             39
end_cluster               36
sloc_eloc_min             15
dtype: int64

In [26]:
def score(pred,valid):
    pred_l = list(pred)
    valid_l = list(valid)
    sum_ = 0
    for i in range(len(pred_l)):
        sum_ += abs(pred_l[i] - valid_l[i])
    return sum_ / (1.0 * len(pred_l))
#     return np.sum(np.abs(pred - valid)) / (1.0 * len(pred))

In [27]:
xgbvalid = xgb.DMatrix(valid_tr[predictors],missing=np.nan)
valid_tr.loc[:,'result'] = model.predict(xgbvalid)
valid_tr['result'].fillna(1,inplace=True)
valid_tr['result']

# xgbvalid = xgb.DMatrix(test[predictors],missing=np.nan)
# test.loc[:,'count'] = model.predict(xgbvalid)
# test['count'].fillna(1,inplace=True)
# test['count']

0       0.939936
1       1.197613
2       1.585420
3       2.494417
4       1.425269
5       0.933754
6       4.807026
7       0.972407
8       0.937116
9       0.956844
10      0.979035
11      0.921314
12      0.931710
13      0.992046
14      1.342978
15      1.015221
16      4.110806
17      1.010267
18      1.095913
19      0.974215
20      1.028091
21      1.481154
22      0.986867
23      1.250049
24      1.002793
25      0.988052
26      0.994430
27      1.402895
28      1.920196
29      0.997159
          ...
4970    1.802277
4971    3.316448
4972    0.920253
4973    1.995911
4974    1.771451
4975    0.919358
4976    1.435446
4977    0.902983
4978    0.992170
4979    1.401407
4980    3.528376
4981    1.928068
4982    0.977304
4983    0.968412
4984    2.768087
4985    2.346734
4986    0.943146
4987    1.811805
4988    2.061287
4989    0.934759
4990    1.932142
4991    1.029202
4992    1.843691
4993    0.947891
4994    3.587604
4995    1.844648
4996    1.230826
4997    0.936110
4998    1.399617
4999    0.981952
Name: result, dtype: float32

In [ ]:
score(valid_tr['result'],valid_tr['demand_count'])

In [ ]:
# test['test_id'] = test['test_id'].astype('int')
# test[['test_id','count']].to_csv('result.csv',index=False)